import {
  BookOpenCheck,
  BrainCircuit,
  EyeOff,
  FolderTree,
  Globe,
  Moon,
  NotebookText,
  Palette,
  Search,
  Sparkles,
  Workflow,
} from 'lucide-react';

import type { TestGroup } from '@/features/tests/pages/testCollectionTypes';

export const testGroups: TestGroup[] = [
  {
    title: 'UI 与主题',
    items: [
      {
        serial: 1,
        title: '错误日志',
        description: '记录软件里出现过的问题、原因、修复办法和后续防复发规则。',
        path: '/error-log',
        icon: NotebookText,
        badge: 'Log',
      },
      {
        serial: 2,
        title: '隐藏页面',
        description: '集中检查没有展示在正式导航里的页面、旧入口和内嵌功能。',
        path: '/hidden-pages-test',
        icon: EyeOff,
        badge: 'Hidden',
      },
      {
        serial: 3,
        title: 'UI库',
        description: '查看软件内可复用 UI、手动上传 UI 和技术词典记录。',
        path: '/software-ui-catalog',
        icon: Palette,
        badge: 'UI',
      },
      {
        serial: 4,
        title: '主题颜色',
        description: '查看主题颜色、深色主题配色和页面色板测试。',
        path: '/theme-colors',
        icon: Moon,
        badge: 'Theme',
      },
      {
        serial: 5,
        title: '水墨2 深度配色预览',
        description: '对照软件标题栏、正文选中、分组、AI 输入区、发送图标、字号控件和首页侧栏的水墨2候选配色。',
        path: '/shuimo2-deep-palette-preview-test',
        icon: Palette,
        badge: 'Shuimo2',
      },
      {
        serial: 9,
        title: '全项目同功能样式对比',
        description: '把空状态、弹窗外壳、分段切换、选中颜色和资料选择行的正式页面现状并排展示。',
        path: '/ui-consistency-comparison-test',
        icon: Palette,
        badge: 'UI Compare',
      },
      {
        serial: 12,
        title: '专业模式九页原样基线',
        description: '直接复用脑洞到综合点评的正式页面、正式导航和正式AI区域，作为后续逐项删减的对照基线。',
        path: '/professional-workbench-baseline-test',
        icon: Workflow,
        badge: 'Pro Baseline',
      },
      {
        serial: 21,
        title: '标准模式设定与创作页面方案',
        description: '直接复用专业模式的设定、章纲、正文和审核逻辑，只精简标准模式的操作入口。',
        path: '/standard-mode-creation-pages-design-test',
        icon: Workflow,
        badge: 'Page Design',
      },
      {
        serial: 25,
        title: '标准模式项目进度与功能取舍',
        description: '集中查看已经完成、部分完成和仍需补齐的流程，按星级判断推荐程度，并勾选要做、暂缓或不做的功能。',
        path: '/standard-mode-project-progress-test',
        icon: Workflow,
        badge: 'Roadmap',
      },
      {
        serial: 35,
        title: '玄幻仙侠字段精简方案',
        description: '对比极简开书、连载实用、剧情优先、世界观优先和分阶段解锁五种字段缩减思路，仅展示方案，不修改正式模板。',
        path: '/fantasy-template-field-reduction-test',
        icon: Sparkles,
        badge: 'Field Plan',
      },
      {
        serial: 38,
        title: '用户系统与用户裂变本地沙箱',
        description: '参考镜语测试沙箱的业务边界，在本地验证会员、积分、管理员、任务冻结结算、一级邀请和退款撤回，不接真实支付。',
        path: '/commercial-sandbox-migration-test',
        icon: BrainCircuit,
        badge: 'Commerce',
      },
    ],
  },
  {
    title: '未做',
    items: [
      {
        serial: 19,
        title: '番茄题材迭代原型',
        description: '用内置浏览器打开番茄小说排行榜，读取当前小说公开信息后做爽点提炼和题材迁移。',
        path: '/tomato-genre-iteration-test',
        icon: Globe,
        badge: 'Tomato',
      },
      {
        serial: 20,
        title: '月下写作内置免费 AI 方案',
        description: '记录配置检测、分档模型推荐、自动下载安装、离线运行和自然语言操作软件的待实现想法。',
        path: '/built-in-ai-product-idea-test',
        icon: BrainCircuit,
        badge: 'Idea',
      },
      {
        serial: 33,
        title: '多 AI 一键生成正文',
        description: '记录一次选择 GPT、Kimi、DeepSeek 等多个模型并行生成正文，再集中对比和选择采用版本的待实现方案。',
        path: '/multi-ai-writing-idea-test',
        icon: Sparkles,
        badge: 'Multi AI',
      },
      {
        serial: 34,
        title: 'AI 排行榜找书',
        description: '记录用户输入找书要求后，由 AI 搜索公开小说排行榜、核对来源并整理匹配书单的待实现想法。',
        path: '/ai-ranking-book-search-idea-test',
        icon: Search,
        badge: 'Book Search',
      },
      {
        serial: 40,
        title: '自定义设定模板',
        description: '暂缓开放用户自由编辑和保存一级到五级设定结构，待新手版稳定后再补充完整校验、导入导出和升级能力。',
        path: '/custom-setting-template-idea-test',
        icon: FolderTree,
        badge: 'Deferred Template',
      },
      {
        serial: 41,
        title: '用户自定义生成顺序',
        description: '暂缓开放生成步骤、依赖关系和先后顺序调整；当前新手版统一使用系统推荐顺序。',
        path: '/custom-generation-order-idea-test',
        icon: Workflow,
        badge: 'Deferred Order',
      },
      {
        serial: 42,
        title: '文风蒸馏与拆书迭代融合方案',
        description: '对比正文后文风审查、拆书提取爽点与节奏、跨类型迁移蓝图，以及两个 MIT 项目的融合和内容权利边界。',
        path: '/story-analysis-fusion-test',
        icon: BookOpenCheck,
        badge: 'Story Fusion',
      },
    ],
  },
];
