import {
  BookOpenText,
  BrainCircuit,
  EyeOff,
  FolderTree,
  Globe,
  Moon,
  NotebookText,
  Palette,
  Search,
  Sparkles,
  Workflow,
} from 'lucide-react';

import type { TestGroup } from '@/features/tests/pages/testCollectionTypes';

export const testGroups: TestGroup[] = [
  {
    title: 'UI 与主题',
    items: [
      {
        serial: 1,
        title: '错误日志',
        description: '记录软件里出现过的问题、原因、修复办法和后续防复发规则。',
        path: '/error-log',
        icon: NotebookText,
        badge: 'Log',
      },
      {
        serial: 2,
        title: '隐藏页面',
        description: '集中检查没有展示在正式导航里的页面、旧入口和内嵌功能。',
        path: '/hidden-pages-test',
        icon: EyeOff,
        badge: 'Hidden',
      },
      {
        serial: 3,
        title: 'UI库',
        description: '查看软件内可复用 UI、手动上传 UI 和技术词典记录。',
        path: '/software-ui-catalog',
        icon: Palette,
        badge: 'UI',
      },
      {
        serial: 4,
        title: '主题颜色',
        description: '查看主题颜色、深色主题配色和页面色板测试。',
        path: '/theme-colors',
        icon: Moon,
        badge: 'Theme',
      },
      {
        serial: 5,
        title: '水墨2 深度配色预览',
        description: '对照软件标题栏、正文选中、分组、AI 输入区、发送图标、字号控件和首页侧栏的水墨2候选配色。',
        path: '/shuimo2-deep-palette-preview-test',
        icon: Palette,
        badge: 'Shuimo2',
      },
      {
        serial: 6,
        title: '作品设定命名与主角能力归属模拟',
        description:
          '按正式设定页模拟作品和人物设定；所有角色将背景目标并入基础档案，并统一境界、功法、战斗和其他技能。',
        path: '/work-setting-taxonomy-proposal-test',
        icon: BookOpenText,
        badge: 'Setting Plan',
      },
      {
        serial: 7,
        title: 'AI可执行设定分类模拟',
        description: '在16号结构上补充力量规则、人设约束、知情边界、动态状态、成长变化与反派计划，模拟AI实际读取效果。',
        path: '/setting-ai-ready-taxonomy-test',
        icon: Sparkles,
        badge: 'AI Ready',
      },
      {
        serial: 8,
        title: '提示词设定与AI创作流程模拟',
        description:
          '根据提示词文件夹整理设定页面，并把白皮书、档案、细纲、续写、审核、发布和状态更新串成一条AI创作流程。',
        path: '/prompt-driven-novel-workspace-test',
        icon: Workflow,
        badge: 'Prompt Workflow',
      },
      {
        serial: 9,
        title: '全项目同功能样式对比',
        description: '把空状态、弹窗外壳、分段切换、选中颜色和资料选择行的正式页面现状并排展示。',
        path: '/ui-consistency-comparison-test',
        icon: Palette,
        badge: 'UI Compare',
      },
      {
        serial: 12,
        title: '专业模式九页原样基线',
        description: '直接复用脑洞到综合点评的正式页面、正式导航和正式AI区域，作为后续逐项删减的对照基线。',
        path: '/professional-workbench-baseline-test',
        icon: Workflow,
        badge: 'Pro Baseline',
      },
      {
        serial: 13,
        title: '标准模式四阶段创作流程',
        description: '模拟建书、脑洞生成与选择、流式设定、连贯章纲、正文编辑和剧情审核的完整新手流程。',
        path: '/standard-mode-four-stage-workbench-test',
        icon: Workflow,
        badge: '4 Stages',
      },
      {
        serial: 14,
        title: '标准模式设定模板选择方案',
        description: '对比直接使用默认模板、改名或增删模板结构并保存，以及从我的模板中再次复用的完整流程。',
        path: '/standard-mode-setting-template-choice-test',
        icon: FolderTree,
        badge: 'Template',
      },
      {
        serial: 21,
        title: '标准模式设定与创作页面方案',
        description: '直接复用专业模式的设定、章纲、正文和审核逻辑，只精简标准模式的操作入口。',
        path: '/standard-mode-creation-pages-design-test',
        icon: Workflow,
        badge: 'Page Design',
      },
      {
        serial: 23,
        title: '标准模式三栏设定页面旧方案',
        description: '保留正式页面替换前的设定目录、设定表单和一键检查三栏布局，供后续单独对比。',
        path: '/standard-mode-compact-setting-workspace-test',
        icon: FolderTree,
        badge: 'Setting UI',
      },
      {
        serial: 25,
        title: '标准模式项目进度与功能取舍',
        description: '集中查看已经完成、部分完成和仍需补齐的流程，按星级判断推荐程度，并勾选要做、暂缓或不做的功能。',
        path: '/standard-mode-project-progress-test',
        icon: Workflow,
        badge: 'Roadmap',
      },
      {
        serial: 28,
        title: '标准模式导航与创作指导新方案',
        description: '对比任务接力、路线站点、阶段目录、焦点伸缩和独立指导卡五套可点击的顶部导航新方案。',
        path: '/standard-mode-guided-navigation-test',
        icon: Workflow,
        badge: 'Guided Nav',
      },
      {
        serial: 29,
        title: '设定模板四级完整展示方案',
        description: '取消画布、缩放和连线，改用一级与二级按钮切换，并把三级设定和四级字段逐组完整展开。',
        path: '/four-level-setting-structure-test',
        icon: FolderTree,
        badge: '4 Levels',
      },
      {
        serial: 30,
        title: '快速设定模板装配器方案',
        description: '通过精简、标准和完整预设起步，用明确复选框增减字段，并在右侧实时查看当前模板汇总。',
        path: '/setting-template-assembler-test',
        icon: FolderTree,
        badge: 'Assembler',
      },
      {
        serial: 31,
        title: '专业模板四级层级多方案',
        description: '为有经验用户提供全景树、四栏联动、路径矩阵和结构卡片四种四级设定展示与自由删减方案。',
        path: '/professional-template-hierarchy-variants-test',
        icon: FolderTree,
        badge: 'Pro Hierarchy',
      },
      {
        serial: 32,
        title: '专业模板DIY编辑多方案',
        description: '对比四栏联动、层级树、分层卡片和路径工作台四种可逐级新增、删除与锁定的模板编辑方案。',
        path: '/professional-template-diy-variants-test',
        icon: FolderTree,
        badge: 'DIY Template',
      },
      {
        serial: 35,
        title: '玄幻仙侠字段精简方案',
        description: '对比极简开书、连载实用、剧情优先、世界观优先和分阶段解锁五种字段缩减思路，仅展示方案，不修改正式模板。',
        path: '/fantasy-template-field-reduction-test',
        icon: Sparkles,
        badge: 'Field Plan',
      },
      {
        serial: 37,
        title: '模板生成步骤设定卡片方案',
        description: '从模板结构读取四级设定，按金、紫、蓝、绿底色标明级别，并把设定卡片嵌入生成步骤里调整顺序。',
        path: '/template-generation-step-cards-test',
        icon: FolderTree,
        badge: 'Step Cards',
      },
      {
        serial: 38,
        title: '用户系统与用户裂变本地沙箱',
        description: '参考镜语测试沙箱的业务边界，在本地验证会员、积分、管理员、任务冻结结算、一级邀请和退款撤回，不接真实支付。',
        path: '/commercial-sandbox-migration-test',
        icon: BrainCircuit,
        badge: 'Commerce',
      },
    ],
  },
  {
    title: 'AI 链路测试',
    items: [
      {
        serial: 16,
        title: '所有提示词',
        description: '整理旧提示词会创建的资料库、模板字段、读取链路和章节发布更新方式。',
        path: '/prompt-library-structure-test',
        icon: FolderTree,
        badge: 'Prompt Lib',
      },
      {
        serial: 17,
        title: '提示词目录预览测试',
        description: '左侧按流程列出提示词文件，右侧预览选中的提示词原文。',
        path: '/prompt-workflow-preview-test',
        icon: FolderTree,
        badge: 'Prompt View',
      },
    ],
  },
  {
    title: '工具测试',
    items: [
      {
        serial: 18,
        title: '内置浏览器',
        description: '测试网页打开、收藏和登录状态保留。',
        path: '/test-browser',
        icon: Globe,
        badge: 'Browser',
      },
    ],
  },
  {
    title: '未做',
    items: [
      {
        serial: 19,
        title: '番茄题材迭代原型',
        description: '用内置浏览器打开番茄小说排行榜，读取当前小说公开信息后做爽点提炼和题材迁移。',
        path: '/tomato-genre-iteration-test',
        icon: Globe,
        badge: 'Tomato',
      },
      {
        serial: 20,
        title: '月下写作内置免费 AI 方案',
        description: '记录配置检测、分档模型推荐、自动下载安装、离线运行和自然语言操作软件的待实现想法。',
        path: '/built-in-ai-product-idea-test',
        icon: BrainCircuit,
        badge: 'Idea',
      },
      {
        serial: 33,
        title: '多 AI 一键生成正文',
        description: '记录一次选择 GPT、Kimi、DeepSeek 等多个模型并行生成正文，再集中对比和选择采用版本的待实现方案。',
        path: '/multi-ai-writing-idea-test',
        icon: Sparkles,
        badge: 'Multi AI',
      },
      {
        serial: 34,
        title: 'AI 排行榜找书',
        description: '记录用户输入找书要求后，由 AI 搜索公开小说排行榜、核对来源并整理匹配书单的待实现想法。',
        path: '/ai-ranking-book-search-idea-test',
        icon: Search,
        badge: 'Book Search',
      },
    ],
  },
];
