import type { ErrorLogEntry } from './errorLogEntryTypes';

export const defaultEntriesPart37: ErrorLogEntry[] = [
  {
    id: 'desktop-startup-console-and-titlebar-flash-001',
    title: '桌面启动不应闪现黑框或只显示标题栏',
    area: '桌面启动器 / Electron 启动过渡 / React 首屏',
    symptom: '双击打开软件时先闪现黑色控制台，随后软件窗口只出现顶部标题栏，正式页面稍后才补齐。',
    cause:
      'VBS 通过 WMI 创建普通 node.exe 进程时仍可能短暂生成控制台；Electron 又在 ready-to-show 或文档加载完成时提前显示，而首个懒加载路由尚未完成渲染。',
    solution:
      'VBS 改用隐藏窗口方式直接启动 Node；Electron 增加与现有浅色界面一致的独立启动窗，主窗口保持隐藏，直到 Suspense 内首个正式路由挂载并通过受信 IPC 报告 renderer-ready 后再切换显示。',
    prevention:
      '启动回归必须锁定隐藏启动器、启动窗安全配置和 renderer-ready 握手；不得重新使用 ready-to-show 作为主窗口的唯一显示条件。',
    keywords: ['启动黑框', '标题栏闪现', '启动窗', 'renderer-ready', 'ready-to-show', 'VBS', 'Electron'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'remember-window-maximized-state-restore-001',
    title: '记住窗口大小应恢复用户保存的最大化状态',
    area: '系统设置 / 记住窗口大小 / Electron 启动状态',
    symptom: '窗口关闭前处于最大化状态，但下次打开仍显示为接近默认尺寸的普通窗口。',
    cause: '状态文件已经正确保存 isMaximized: true，启动逻辑却主动忽略该字段，只使用最大化前的普通窗口边界。',
    solution:
      '启动读取到最大化状态时，在恢复安全的普通窗口边界后调用 BrowserWindow.maximize()；保存状态只应用一次，避免后续显示回调覆盖用户刚选择的固定尺寸。',
    prevention:
      '窗口记忆回归测试必须同时锁定普通窗口尺寸、最大化状态和预设切换，禁止重复启动回调再次套用旧状态。',
    keywords: ['记住窗口大小', '最大化', 'isMaximized', 'BrowserWindow', '启动恢复'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'electron-smoke-window-state-isolation-001',
    title: '自动化启动测试不应覆盖用户记住的窗口尺寸',
    area: '系统设置 / 记住窗口大小 / Electron 自动化测试',
    symptom:
      '已经开启“记住窗口大小”，用户也调整过常用尺寸，但运行桌面 smoke 或路由测试后，下次启动又变成接近默认的 1374 × 777。',
    cause:
      '测试虽然通过 --user-data-dir 使用临时 Electron 用户目录，窗口状态存储却固定写入 appData 下的正式共享目录，导致测试窗口关闭时把真实 window-state.json 覆盖。',
    solution:
      '窗口状态存储支持显式 stateDir；无界面 smoke 模式改为使用临时 userData 目录，并禁用正式目录和旧状态文件迁移，正式启动仍使用共享目录。',
    prevention:
      '所有会保存窗口状态的自动化启动必须使用隔离目录；回归测试同时锁定隔离目录的读写结果，并确认正式共享状态文件内容不发生变化。',
    keywords: ['记住窗口大小', 'Electron smoke', 'window-state.json', 'stateDir', '测试隔离', '用户数据'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'remember-window-size-startup-clamp-and-badge-wrap-001',
    title: '记住窗口大小不应被启动高度限制覆盖或导致分辨率跳行',
    area: '系统设置 / 记住窗口大小 / Electron 启动尺寸',
    symptom:
      '已开启记住窗口大小后，下次启动仍未恢复保存尺寸；默认和当前分辨率先同排，真实尺寸返回后又突然变成上下两行。',
    cause:
      '主进程把所有保存高度强制限制在工作区的75%，覆盖了正常可容纳的保存尺寸；分辨率徽标使用自动换行布局，文本宽度变化会改变行数。',
    solution: '保存尺寸只在超过显示器实际工作区时收缩；正常尺寸原样恢复。分辨率固定为默认在上、当前在下的纵向两行。',
    prevention:
      '窗口记忆测试必须覆盖可容纳尺寸的精确恢复和超大尺寸安全收缩；异步尺寸信息不得依赖自动换行决定最终布局。',
    keywords: ['记住窗口大小', '2064×1120', '1366×768', 'Electron', '工作区', '分辨率跳动', 'windowBounds'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'keep-associations-checkbox-and-session-lifecycle-001',
    title: '关联有效期应由保持关联开关控制真实会话清理',
    area: '测试设置 / 关联设置 / 软件会话生命周期',
    symptom: '关联设置只显示说明但无法操作；关闭软件后资料、本章和脑洞等关联的清理或保留行为与用户预期不一致。',
    cause:
      '界面没有持久化开关，清理逻辑固定执行；关联数据还绑定运行时 ID，即使存储未删除，下次启动也会被判定为旧关联。',
    solution:
      '将关联有效期改为默认不勾选的“保持关联”复选框；未勾选时关闭和下次启动清理全部关联，勾选时保留数据并迁移到新运行时 ID。',
    prevention:
      '会话级设置必须同时覆盖界面、关闭事件、启动兜底和运行时数据校验；回归测试需覆盖开关两种状态及窗口暂时隐藏。',
    keywords: ['保持关联', '关联设置', '资料', '本章', '脑洞', '关闭软件', 'runtime ID', 'workbenchAssociationCleanup'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'window-settings-resolution-badges-layout-shift-001',
    title: '窗口设置分辨率信息不应延迟出现并挤动按钮',
    area: '设置 / 系统设置 / 窗口大小卡片',
    symptom: '进入设置时分辨率徽标先缺失，IPC 返回后突然出现，卡片内容发生跳动；已开启按钮还会换行到左下角。',
    cause: '当前窗口尺寸仅在异步设置结果存在时才渲染，底部又使用可换行 flex，新增徽标后会重新计算按钮位置。',
    solution: '首帧使用 1366 × 768 默认尺寸完整占位；两个卡片底部改为固定的左侧分辨率、右侧操作按钮两列布局。',
    prevention: '异步元数据必须从首帧保留相同结构和高度；卡片底部信息与操作应使用固定网格列，并由结构测试锁定。',
    keywords: ['系统设置', '窗口大小', '分辨率', '布局跳动', '已开启', '恢复默认', 'WindowSettingsCompactSection'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'navigation-settings-pointer-sort-flicker-and-reset-001',
    title: '导航设置拖拽排序不应闪烁或被保存归一化重置',
    area: '软件设置 / 导航设置 / 拖拽排序',
    symptom: '拖动导航项换位置时列表在相邻位置间疯狂闪烁，轻微移动就反复换位，松手后部分位置又恢复原样。',
    cause:
      '导航行同时启用原生 drag 和自定义 pointer 两套拖拽事件，实时换位预览又会改变鼠标下方目标；保存归一化还强制移动番茄浏览器，覆盖用户排序。',
    solution:
      '导航项改为单一指针拖拽，列表保持稳定并只显示落点线，松手时一次性保存；提高激活和换目标阈值，并取消保存阶段的固定路由重排。',
    prevention:
      '同一排序控件只能使用一套拖拽事件；拖动预览不得改变命中目标的 DOM 顺序；导航归一化必须保留用户自定义顺序并由回归测试锁定。',
    keywords: ['导航设置', '拖拽排序', 'pointer', '闪烁', '灵敏度', '自定义顺序', 'NavSettingsModal'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'setting-name-fields-unified-with-role-name-001',
    title: '各设定页名称输入框应与人物姓名保持统一',
    area: '工作台 / 设定页 / 名称输入框视觉统一',
    symptom:
      '人物姓名使用浮动边框输入框，而作品、势力、道具、怪物和伏笔页面的设定名有全宽或普通横排输入框，宽度和视觉层级不一致。',
    cause: '结构化设定标题和普通设定标题沿用了两套输入布局，且伏笔页还根据字段数量使用了特殊网格标题行。',
    solution:
      '所有设定名称和结构化标题统一复用与人物姓名相同的浮动边框样式、字体和 232px 宽度，其他模型和提示词输入框保持原尺寸。',
    prevention:
      '新增设定页标题时必须复用名称输入框样式，不得重新引入全宽或外置标签布局；回归测试需覆盖作品、势力、道具、怪物、伏笔和人物六类入口。',
    keywords: ['设定名', '人物姓名', '输入框宽度', '浮动边框', '结构化设定', 'workbenchSettingEditor'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'role-create-dialog-remove-group-and-design-001',
    title: '新建角色弹窗应聚焦角色名字并避免多余分组选择',
    area: '工作台 / 人物设定 / 新建角色弹窗',
    symptom: '新建角色弹窗视觉层级偏重，说明文字强调所属分组，且分组选择行占用空间，用户无法快速完成角色创建。',
    cause: '角色创建沿用了设定创建的通用分组选择控件，没有根据角色默认当前分组的流程收敛弹窗内容。',
    solution:
      '将测试08的方案C迁移到正式新建角色弹窗，移除英文装饰，只保留标题、角色名字输入和操作按钮，示例改为“例如：萧炎”；分组由当前上下文自动决定，设定弹窗仍保留所属分组选择，并删除临时测试页面、入口和路由。',
    prevention:
      '复用创建弹窗时应按对象类型检查是否真的需要分组选择；角色创建回归需确认无英文装饰、示例名正确且测试入口已清理，设定创建回归需确认选择控件仍可用。',
    keywords: ['新建角色', '角色弹窗', '所属分组', '方案C', '萧炎', '人物设定'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'workbench-setting-embedded-title-and-count-001',
    title: '工作台设定标题应统一嵌入边框且正确统计数量',
    area: '工作台 / 设定 / 字段标题与顶部统计',
    symptom:
      '设定名使用普通输入框，与故事类型、世界观等浮动边框不一致；人物姓名标签压线时显得突兀；顶部设定数没有包含人物和伏笔条目。',
    cause:
      '部分作品、道具和资源结构化模板没有配置标题字段，仍回退到普通输入框；人物头部容器受浮动字段的全宽规则影响而被拉长，标题行没有固定紧凑高度；工作流统计把设置存储中的非脑洞遗留条目也算入总数。',
    solution:
      '为未单独声明标题的结构化模板统一回退使用“设定名”浮动边框标签；将人物姓名字段限制为 220px 并固定头部两行高度；顶部设定数只统计“作品设定”和“人物设定”存储条目，使其与六个分类的实际数量一致。',
    prevention:
      '新增设定类型时必须同时检查设定名、世界观、势力、道具、怪物等标题的浮动边框样式；人物头部回归需检查字段宽度和标题行高度；顶部分类数量必须与作品、人物、势力、道具、怪物、伏笔六类之和核对。',
    keywords: ['设定名', '故事类型', '人物姓名', '世界观', '伏笔线索', '设定数量', 'WorkbenchSettingEditor'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'launcher-stale-vite-optimized-deps-recovery-001',
    title: 'Vite 端口可访问时仍应检查优化依赖是否失效',
    area: '桌面启动器 / Vite 开发服务器 / 依赖缓存',
    symptom:
      'Vite 进程和端口看似正常，但 `.vite/deps` 中的优化依赖过期或损坏时，页面仍可能白屏、依赖 404 或模块加载失败。',
    cause: '启动器原来只检查端口和依赖指纹，无法识别指纹未变但 Vite 优化依赖文件已经不可访问的情况。',
    solution:
      '在复用已运行的 Vite 前读取主模块，抽样检查最多 12 个 `.vite/deps` 模块；检测失败时复用项目级 Vite 进程清理，删除 `node_modules/.vite` 并重启服务。',
    prevention: '启动器回归测试应同时覆盖主模块正常、优化依赖失效和主模块不可访问，并确保清理范围只限当前项目。',
    keywords: ['Vite', 'optimized deps', 'node_modules/.vite', '白屏', '启动器', 'launch-xinyuexia.mjs'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'default-cover-custom-history-library-001',
    title: '默认封面设置应保留可选的自定义封面历史',
    area: '设置 / 默认封面设置 / 自定义封面库',
    symptom: '右侧自定义封面区域只能保存一张图片，上传新封面会覆盖旧封面，历史封面无法再次选为当前使用。',
    cause: '自定义封面只使用单值存储键和固定 custom-default-cover ID，没有独立的历史记录集合和封面 ID。',
    solution:
      '增加自定义封面历史列表，按最新上传排序并最多保留20张；旧单张存储自动迁移，每张历史封面都支持点击设为当前使用和单独删除。',
    prevention:
      '封面设置回归测试应覆盖旧数据迁移、多张记录顺序、20张上限、历史项重新选择和单项删除，避免恢复单图覆盖逻辑。',
    keywords: ['默认封面', '自定义封面', '历史记录', '20张', '当前使用', 'localStorage'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'move-association-and-app-icon-to-test-settings-001',
    title: '关联设置和软件图标应归入测试设置',
    area: '设置 / 用户设置与测试设置 / 功能归属',
    symptom: '关联设置和软件图标仍显示在用户设置的系统设置子导航中，与其测试和低频工具属性不符。',
    cause: '统一设置页继续沿用了窗口、关联设置、软件图标共用系统设置子标签的旧结构。',
    solution:
      '移除用户设置中的系统设置子导航，仅保留窗口设置；将关联设置和软件图标作为独立顶部入口加入测试设置，并复用原功能页面。',
    prevention:
      '设置层级回归测试应断言用户设置不包含关联设置和软件图标，测试设置包含两个独立入口，且原功能内容仍可访问。',
    keywords: ['设置', '用户设置', '测试设置', '关联设置', '软件图标', 'SettingsPage'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'retire-script-prompts-and-modal-category-create-001',
    title: '提示词管理应只保留小说提示词并用弹窗新增分类',
    area: '提示词管理 / 剧本提示词 / 分类创建',
    symptom: '提示词管理仍提供剧本提示词页面；新增分类需要在分类栏旁的常驻输入框中输入，挤占分类展示空间。',
    cause: '提示词页面继续维护 novel 和 script 两套类型分支，分类创建操作则直接绑定在工具栏输入框上。',
    solution:
      '删除剧本提示词标签、类型、筛选、创建、导入导出和回收站分支，并清理存储中的剧本提示词；新增分类改为按钮触发的软件风格输入弹窗，确认后创建。',
    prevention:
      '回归测试应断言提示词页只显示小说提示词、剧本类型无法重新进入源码和存储，同时覆盖新增分类弹窗的输入与确认流程。',
    keywords: ['提示词管理', '小说提示词', '剧本提示词', '新增分类', '输入弹窗', 'PromptsPage'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'chapter-review-detail-label-pill-style-001',
    title: '剧情审核说明和建议标签应与通过状态保持一致',
    area: '工作台 / 剧情审核 / 审核项详情',
    symptom: '审核项展开后，说明和建议使用灰色普通小标题，与右上角通过胶囊的视觉样式不一致。',
    cause: '详情标题沿用了弱提示文字样式，没有复用审核状态所采用的浅绿色圆角胶囊语言。',
    solution: '将说明和建议改为与通过状态一致的浅绿色背景、深绿色文字和全圆角胶囊，并保留原详情内容与展开逻辑。',
    prevention: '审核结果中的同级短标签应使用统一的胶囊样式，回归测试需同时锁定说明和建议两个标签。',
    keywords: ['剧情审核', '说明', '建议', '通过', '胶囊标签', 'ChapterReviewPreview'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'chapter-editor-obsolete-review-size-settings-001',
    title: '作品编辑器设置不应保留失效的审核控件尺寸项',
    area: '工作台 / 作品编辑器设置',
    symptom:
      '设置弹窗显示四行审核按钮、模型框和提示词框尺寸项，但多数没有连接正式控件，模型项也无法独立控制当前组合框。',
    cause: '审核区改为自适应的模型与提示词组合框后，旧字段尺寸数据、存储和样式传递没有同步清理。',
    solution: '删除四项旧尺寸设置及其状态、无效预览和样式传递，弹窗只保留仍有效的导航宽度统一设置。',
    prevention: '控件合并或改为自适应布局时，应同步搜索并删除旧配置行、预览和调用链。',
    keywords: ['作品编辑器设置', '旧设置', '字段尺寸', '模型提示词组合框', '导航宽度统一'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'prompt-editor-header-density-and-floating-fields-001',
    title: '编辑提示词弹窗标题栏过高且元数据字段视觉不统一',
    area: '提示词管理 / 编辑提示词 / 弹窗布局',
    symptom: '编辑提示词顶部标题栏占用高度过多，提示词内容字号偏小，名称和说明仍使用左侧外置标签，与内容编辑框不一致。',
    cause: '标题栏沿用大弹窗的宽松垂直内边距，内容编辑器保留16px字号，元数据字段没有复用浮动边框标签结构。',
    solution: '将标题栏从约80px压缩到约48px；提示词内容增大到19px；名称和说明改为标签嵌入上边框的浮动输入框。',
    prevention: '提示词编辑弹窗回归测试应锁定标题栏内边距、19px内容字号，以及名称和说明两个嵌入式边框标签。',
    keywords: ['提示词管理', '编辑提示词', '标题栏高度', '字体大小', '浮动标签', 'PromptEditorModal'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'detail-outline-title-volume-and-chapter-number-001',
    title: '章纲标题应同时显示卷序号和章节序号',
    area: '工作台 / 章纲 / 章纲编辑框标题',
    symptom: '章纲编辑框标题只显示“第1章章纲”，无法从标题判断当前章节属于哪一卷。',
    cause: '章纲标题只拼接了章节序号，没有读取当前章所在卷的名称，且章节序号与“章纲”之间缺少空格。',
    solution: '章纲标题改为读取当前卷名称和章节序号，按“第一卷 第1章 章纲”的格式显示。',
    prevention: '章纲标题回归测试必须同时锁定当前卷名称、章节序号和空格格式，避免再次退化为仅显示章节序号。',
    keywords: ['章纲', '卷序号', '章节序号', '章纲标题', 'OutlineWorkspaceView'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'detail-outline-border-font-tools-and-inline-counts-001',
    title: '章纲和状态变化应使用独立的框边字号与标题字数',
    area: '工作台 / 章纲 / 章纲与状态变化编辑框',
    symptom: '章纲字号位于页面右上角，章纲框重复显示章节名称，两个编辑框的字数又分散在右下角；状态变化没有独立字号。',
    cause: '章纲页沿用全局标题栏字号入口和通用右下角字数组件，状态变化 textarea 直接复用了章纲字号配置。',
    solution:
      '删除章纲框右上章节名称；将章纲、状态变化字号分别嵌入各自右上边框并独立保存；字数合并到左上标题，显示为“章纲 X字”和“状态变化 X字”。',
    prevention:
      '同页不同编辑区域需要独立字号时必须使用独立配置键；框体字数优先与标题同行，回归测试锁定无右下角重复统计和无章节名称残留。',
    keywords: ['章纲字号', '状态变化字号', '透明背板', '边框嵌入', '字数统计', '未命名章节'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'structured-setting-basic-label-unification-001',
    title: '结构化设定首个标签应统一为基础设定',
    area: '工作台 / 设定 / 结构化设定标签',
    symptom: '部分设定类型显示“固定设定”，人物和其他区域则显示“基础设定”，同一层级名称不一致。',
    cause: '结构化设定标签、默认选中值和部分字段分组仍使用早期的“固定设定”文案。',
    solution: '将结构化设定的首个标签、默认选中值及势力、功法、特殊资源等分组标题统一改为“基础设定”。',
    prevention: '设定页同级标签统一使用“基础设定”；回归测试应断言结构化设定源码和可见标签中不再出现“固定设定”。',
    keywords: ['固定设定', '基础设定', '结构化设定', '标签统一', 'STRUCTURED_SETTING_TABS'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'detail-outline-inline-word-count-color-spacing-001',
    title: '章纲标题字数应恢复双色并保留三字符间距',
    area: '工作台 / 章纲 / 标题字数统计',
    symptom: '字数移动到标题后变成与标题相同的黑色，并且紧贴“章纲”或“状态变化”文字。',
    cause: '标题内直接拼接了纯文本字数，没有复用原字数统计的品牌蓝数字和灰色单位，也没有独立间距。',
    solution: '新增标题内字数组件，数字使用品牌蓝、“字”使用灰色，并通过 3ch 左外边距稳定保留三个空格距离。',
    prevention:
      '移动字数统计位置时应同时保留原有颜色语义；需要固定多个空格时使用 ch 间距，不能依赖会被 HTML 合并的普通空格。',
    keywords: ['章纲字数', '状态变化字数', '品牌色', '三个空格', '3ch'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'detail-outline-border-font-input-style-isolation-001',
    title: '章纲框边字号输入框不应继承正文浮动框尺寸',
    area: '工作台 / 章纲 / 框边字号工具',
    symptom: '字号工具中间的数字框被拉成约66px高的大圆角框，减号和加号悬在两侧，控件整体变形。',
    cause:
      '字号工具嵌入章纲浮动框后，其中的 input 命中了浮动框通用 input 样式；新工具类没有加入原字号控件的高优先级尺寸选择器。',
    solution:
      '将章纲框边字号工具加入字号容器、按钮、图标和输入框的隔离选择器，强制恢复1.76rem高度、2rem数字宽度和无圆角中段。',
    prevention:
      '在浮动字段内部嵌入带 input 的工具时，必须为内部 input 提供高于浮动字段通用规则的完整尺寸覆盖，并用源码测试锁定。',
    keywords: ['章纲字号', '状态变化字号', '输入框变形', '样式继承', 'FontSizeStepper'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'detail-outline-title-remove-volume-prefix-001',
    title: '章纲标题应从章节序号开始显示字数',
    area: '工作台 / 章纲 / 章纲标题与字数',
    symptom: '章纲标题前面带有卷名称，导致字数统计位置随卷名称长度变化，标题信息显得过长。',
    cause: '章纲标题复用了卷名称和章节名称组合，字数统计只使用相对间距。',
    solution: '章纲标题改为“第X章 章纲”，删除卷名称；字数统计使用2ch的固定标题间距，保持紧凑且清晰。',
    prevention: '章纲标题只保留章节序号和章纲语义，字数统计间距需要固定时使用独立 spacingClassName。',
    keywords: ['第1章 章纲', '删除第一卷', '字数间距', '2ch'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'detail-outline-font-tool-layer-and-panel-gap-001',
    title: '章纲字号工具应置于边框上层且两个编辑框保持间距',
    area: '工作台 / 章纲 / 字号工具与编辑框间距',
    symptom: '右上角字号工具被章纲边框或浮动元素遮挡，章纲和状态变化两个编辑框在纵向上贴得过紧。',
    cause: '字号工具层级低且未建立独立层叠上下文；两个编辑框使用16px间距，工具高度让视觉间距进一步被压缩。',
    solution: '将字号工具提升到 z-index 60 并建立独立层叠上下文；编辑框间距调整为约24px。',
    prevention: '边框嵌入工具必须明确高于标签和边框的层级；上下相邻的大型编辑框应按工具高度预留稳定间距。',
    keywords: ['章纲字号', 'z-index', '层叠上下文', '编辑框间距', 'gap-6'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'role-name-font-size-consistency-with-base-fields-001',
    title: '人物姓名输入框字号应与外貌字段统一',
    area: '工作台 / 人物设定 / 基础设定字号',
    symptom: '点击人物姓名输入框时，文字字号与“外貌”等基础设定字段不一致，聚焦前后出现视觉跳变。',
    cause:
      '人物姓名输入框写死17px，而外貌等字段使用统一的 roleTextFontSize；浮动输入框聚焦时的通用规则进一步放大了差异。',
    solution: '人物姓名输入框改为使用 roleTextFontSize，并移除写死的17px样式。',
    prevention: '人物设定基础字段和标题输入框应共用 roleTextFontSize，禁止在单个字段上写死字号。',
    keywords: ['人物姓名', '外貌', '字号统一', 'roleTextFontSize', '聚焦跳变'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'setting-and-role-name-label-focus-weight-001',
    title: '设定名和人物姓名标签聚焦前后应保持粗体',
    area: '工作台 / 设定与人物设定 / 标题输入框标签',
    symptom: '点击设定名或人物姓名输入框后，边框上的标签会从粗体变回普通字重，与外貌字段标题不一致。',
    cause: '名称标签虽声明900字重，但后面的浮动框聚焦通用规则以相同优先级覆盖为500。',
    solution: '将设定名和人物姓名专用标签字重固定为900并提高声明优先级，确保聚焦、已有值和未聚焦状态一致。',
    prevention: '专用浮动标签如果需要稳定视觉，应显式覆盖通用聚焦态的字号、字重和变换规则，并增加聚焦前后回归断言。',
    keywords: ['设定名', '人物姓名', '外貌', '字体粗细', 'focus-within', 'font-weight'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'text-audit-revised-empty-waiting-label-001',
    title: '文本审核未识别修改后全文时应显示等待提示',
    area: '工作台 / 文本审核 / 审核后预览',
    symptom: '文本审核尚未形成可解析的修改后全文时，审核后区域显示“未识别到【修改后全文】”，看起来像 AI 已经失败。',
    cause: '审核后预览把尚未完成的流式输出和最终格式错误共用一条提示文案。',
    solution: '将未解析修改后全文的提示改为“AI正在思考，请稍后……”，段落数量不一致等已确认的格式问题继续保留具体提示。',
    prevention: '流式 AI 输出未完成时应显示等待状态，只有请求结束后仍无法解析时才显示格式错误说明。',
    keywords: ['文本审核', '修改后全文', 'AI正在思考', '审核后预览'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'text-audit-continuous-review-allows-paragraph-count-drift-001',
    title: '文本审核段落数不一致时仍应进入逐段审核',
    area: '工作台 / 文本审核 / 逐段审核',
    symptom: '原文与修改后全文段落数量不一致时，正式页显示整列错误提示，和15号测试的逐段审核行为不一致。',
    cause: '正式页用段落数量相等作为连续审核组件的进入条件，阻断了缺失段落的局部差异展示。',
    solution: '改为只要解析出修改后全文就进入逐段审核，按原文索引映射，缺少的审核后段落按空内容处理。',
    prevention: '逐段审核不得被整体数量校验阻断；数量差异应在对应段落中呈现，且正式页与验证测试使用同一映射规则。',
    keywords: ['文本审核', '15号测试', '逐段审核', '段落数量', 'ChapterTextAuditContinuousReview'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'setting-name-role-name-spacing-font-and-label-lock-001',
    title: '设定名和人物姓名应统一间距字号并固定标签',
    area: '工作台 / 设定页 / 名称框视觉统一',
    symptom: '顶部作品设定、人物设定标签页到名称框的间距不一致；人物姓名字号偏小；点击设定名时标签会跳动。',
    cause: '结构化标题行叠加了额外顶部内边距，人物姓名使用正文字号内联覆盖，浮动标签聚焦态未锁定位置。',
    solution: '统一名称框距标签页12px，名称输入统一17px，并固定设定名和人物姓名标签的边框上沿位置。',
    prevention: '名称框布局只保留一层顶部间距；标题输入禁止使用正文字号覆盖；浮动标签必须锁定聚焦前后位置。',
    keywords: ['设定名', '人物姓名', '顶部间距', '17px', '浮动标签', '聚焦跳动'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'role-identity-and-life-status-group-001',
    title: '身份定位和生存状态应组成紧凑人物状态组',
    area: '工作台 / 人物设定 / 顶部字段与角色导航',
    symptom: '身份定位样式突兀，存活死亡切换贴在最右侧，导航角色名无法体现生存状态。',
    cause: '身份定位沿用青色胶囊选择框，状态切换被标题行两端对齐推远，导航未渲染lifeStatus。',
    solution: '身份定位改为黑色浮动边框；状态切换跟在右侧并用绿色或红色选中态；角色名后显示对应颜色状态灯。',
    prevention: '人物短字段按语义相邻排列；存活和死亡颜色必须在编辑器与导航保持一致。',
    keywords: ['身份定位', '存活', '死亡', '状态灯', '人物导航'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'role-life-status-color-scope-001',
    title: '生存状态颜色只显示在导航状态灯',
    area: '工作台 / 人物设定 / 生存状态颜色',
    symptom: '编辑区存活死亡按钮被显示成绿色和红色，用户要求恢复原有按钮颜色，只在导航角色名右侧显示绿点或红点。',
    cause: '导航状态灯的语义颜色被错误复用到编辑区状态切换按钮。',
    solution: '恢复编辑区青色选中、灰色未选中样式，绿色和红色仅用于导航角色名后的状态灯。',
    prevention: '实现颜色状态时必须区分导航提示灯与编辑控件选中态，避免跨区域复用颜色语义。',
    keywords: ['存活', '死亡', '导航状态灯', '绿色圆点', '红色圆点'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'setting-name-field-size-and-gap-stable-across-tabs-001',
    title: '切换设定页时名称框尺寸和间距保持稳定',
    area: '工作台 / 作品设定与人物设定 / 名称框布局',
    symptom: '切换不同设定页面时设定名框的宽度、高度或距上方标签页间距产生体感差异。',
    cause: '名称框受页面父级 max-width 和各自包裹间距影响，没有共享的强制尺寸和顶部间距。',
    solution: '统一名称框为232×48px，所有设定编辑器使用共享容器类并固定顶部12px间距，只允许标题文字变化。',
    prevention: '名称框尺寸和顶部间距必须由共享样式统一约束，新增设定页不得覆盖这些值。',
    keywords: ['设定名', '人物姓名', '切换页面', '232px', '48px', '12px间距'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'setting-role-name-label-first-glyph-alignment-001',
    title: '设定名和人物姓名标签首字与输入文字对齐',
    area: '工作台 / 设定页 / 名称框标签对齐',
    symptom: '点击名称输入框时标签会水平移动，标签首字与输入文字首字没有竖直对齐。',
    cause: '标签左偏移20px而输入文字左 padding为28px，浮动缩放原点也未显式锁定。',
    solution: '名称标签统一使用28px左起点并固定左侧变换原点，聚焦前后保持同一水平位置。',
    prevention: '名称标签位置必须与输入文字 padding 共用基准，并锁定 transform-origin。',
    keywords: ['设定名', '人物姓名', '首字对齐', '水平位移', 'transform-origin'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'setting-role-name-label-disable-focus-motion-001',
    title: '设定名和人物姓名标签点击时保持完全静止',
    area: '工作台 / 设定页 / 名称标签聚焦状态',
    symptom: '名称标签位置已对齐，但点击输入框时仍会轻微移动一下。',
    cause: '名称标签继续继承通用浮动标签的150ms过渡，聚焦样式重算时产生亚像素动画。',
    solution: '普通、聚焦和已有值状态使用同一强制样式，并关闭名称标签的transition和animation。',
    prevention: '固定边框标签不得继承通用浮动动画，回归测试需锁定无过渡声明。',
    keywords: ['设定名', '人物姓名', '点击移动', 'transition', '固定标签'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'setting-name-static-frame-caption-slot-001',
    title: '切换设定标签时名称框应保持完全静止',
    area: '工作台 / 设定页 / 名称框跨标签一致性',
    symptom: '作品设定、人物设定、势力设定等标签之间切换时，名称框仍有伸缩或轻微位移的体感。',
    cause: '名称框继续复用通用浮动标签，标题背板宽度随标题字数变化，导致上边框断口长度不同；聚焦时还会重新匹配通用浮动状态。',
    solution: '使用独立 WorkbenchNameField 统一名称框 DOM，固定232×48px外框、76px标题槽和28px文字起点，并让标题脱离通用浮动标签规则。',
    prevention: '跨页面名称框必须共用固定结构和固定标题槽，只允许标题文字变化；不得让标题遮挡宽度或聚焦状态改变外框观感。',
    keywords: ['设定名', '人物姓名', '切换标签', '固定标题槽', '边框断口', 'WorkbenchNameField'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'setting-name-caption-empty-right-space-001',
    title: '名称框标题右侧不应出现固定空白',
    area: '工作台 / 设定页 / 名称框标题布局',
    symptom: '名称框尺寸虽然固定，但设定名或其他标题右侧出现明显空白，切换页面后标题和值的关系仍显得不一致。',
    cause: '标题背板为了固定边框断口设置了固定宽度，短标题也占用了最长标题的空间。',
    solution: '保持名称框232×48px和文字起点不变，将标题背板改为内容自适应宽度，并让名称框在父级布局中保持起始位置。',
    prevention: '固定名称框的几何尺寸，不固定标题背板宽度；所有同类设定页必须复用统一名称框组件。',
    keywords: ['设定名', '人物姓名', '标题右侧空白', '自适应标题背板', '固定框尺寸'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'foreshadow-header-code-width-and-count-001',
    title: 'Foreshadow header code field should be narrow and omit counts',
    area: 'Workbench / Settings / Foreshadow fields',
    symptom: 'The foreshadow code field was as wide as chapter fields and the three top metadata fields displayed 0-word counts.',
    cause: 'The code field had no dedicated width constraint and the metadata labels reused the generic word-count renderer.',
    solution: 'Set the foreshadow code field to 176px and render only the metadata labels and values in the top row.',
    prevention: 'Use content-sized fixed widths for bounded identifiers and decide word-count display per metadata field instead of inheriting it globally.',
    keywords: ['foreshadow code', '176px', 'remove word count', 'metadata field'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'foreshadow-code-width-overridden-by-floating-field-001',
    title: '伏笔编号框宽度不得被通用浮动字段覆盖',
    area: '工作台 / 设定页 / 伏笔编号框',
    symptom: '伏笔编号框配置为窄宽度后仍横跨顶部大部分区域。',
    cause: '通用浮动字段的 width: 100% 覆盖了编号字段的宽度工具类。',
    solution: '增加专用字段类，同时锁定 flex-basis、width、min-width 和 max-width 为176px。',
    prevention: '结构化短字段必须同时锁定 flex 基准和宽度上下限，不能只设置单个宽度类。',
    keywords: ['伏笔编号', '176px', 'width:100%', 'flex-basis', '专用字段类'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'structured-setting-empty-entry-counts-template-001',
    title: '空结构化伏笔不应统计字段模板文字',
    area: '工作台 / 设定页 / 侧栏字数统计',
    symptom: '伏笔字段没有实际内容，但侧栏显示44字。',
    cause: '统计直接计算结构化序列化正文，把字段标题、标点和换行模板算入字数。',
    solution: '解析结构化字段后只拼接各字段实际值进行统计，空字段返回0字。',
    prevention: '结构化设定统计必须基于字段值，不能统计带标题的存储格式。',
    keywords: ['伏笔', '空内容', '44字', '结构化字段', '侧栏统计'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'setting-header-caption-identity-variant-001',
    title: 'Setting header captions and identity positioning need one visual baseline',
    area: 'Workbench / Settings / structured headers and character identity',
    symptom: 'The foreshadow name and foreshadow code captions used different font sizes and weights, while identity positioning appeared visually detached from the character name and life status.',
    cause: 'WorkbenchNameField used a separate caption scale from the shared floating-outline field, and the identity control was only represented by the current cyan capsule treatment.',
    solution: 'Align WorkbenchNameField captions and values with the foreshadow-code baseline, then add four in-app identity-position variants with an embedded outline option marked as recommended.',
    prevention: 'Use the shared name-field and floating-outline typography for all setting headers, and compare new identity treatments in the test collection before migrating one to the formal role editor.',
    keywords: ['setting header', 'foreshadow code', 'identity position', 'font baseline', 'test collection'],
    updatedAt: '2026-07-20',
  },
];
