import type { ErrorLogEntry } from './errorLogEntryTypes';

export const defaultEntriesPart36: ErrorLogEntry[] = [
  {
    id: 'workbench-brainstorm-directory-open-stutter-001',
    title: '打开书籍脑洞时左侧目录树不应短暂卡顿',
    area: '工作台 / 脑洞 / 左侧目录树',
    symptom: '每次打开一本书籍的脑洞时，左侧目录树会停顿一下再稳定显示；脑洞数量和内容越多越明显。',
    cause:
      '脑洞与大纲切换使用不同 key，导致资料库面板反复卸载和挂载；挂载后又重复读取整库数据、宽度和展开状态，同一条目录内容在一次渲染中还会被多次 JSON.parse。',
    solution:
      '书籍工作台加载时在隐藏区域预备脑洞资料库面板，进入脑洞时直接显示并保留同一实例；首次挂载跳过重复整库初始化，切换标签前同步恢复宽度和展开状态，并在单次目录渲染中缓存条目解析结果。',
    prevention:
      '大型目录面板应保持实例稳定；初始化数据只读取一次，属性切换只更新目标标签状态，派生解析结果应缓存后复用。',
    keywords: ['脑洞', '目录树卡顿', '重复挂载', '重复初始化', 'JSON.parse', 'WorkbenchCreationFlowContent'],
    updatedAt: '2026-07-14',
  },
  {
    id: 'desktop-startup-height-work-area-ratio-001',
    title: '软件启动窗口高度不应接近或超出屏幕',
    area: '桌面端 / 启动窗口 / 尺寸记忆',
    symptom: '软件记住较大的旧窗口尺寸后，再次打开时窗口高度几乎占满屏幕，分辨率或工作区变化后还可能越过可用区域。',
    cause:
      '启动时直接恢复 window-state.json 中的高度，只检查窗口是否与某块屏幕相交，没有按当前显示器工作区限制恢复高度。',
    solution:
      '启动时按窗口所在显示器的 workArea 重新计算尺寸，将高度上限设为工作区的 75%，超限后垂直居中；启动阶段不再恢复最大化状态。',
    prevention: '恢复持久化窗口尺寸时必须以当前显示器工作区为边界，不能把旧分辨率下保存的尺寸原样应用。',
    keywords: ['启动窗口', '75%', 'workArea', 'window-state.json', 'fitStartupBoundsToWorkArea'],
    updatedAt: '2026-07-14',
  },
  {
    id: 'novel-overview-number-auto-fit-001',
    title: '作品概览数字应随卡片宽度自动缩放',
    area: '我的小说 / 作品概览 / 四个统计小卡片',
    symptom: '缩放软件或缩窄作品概览卡片后，作品数、昨日更新、字数和平均字数会越过统计卡片边框。',
    cause: '数值列强制保留 86px 最小宽度并使用固定区间字号，标签、间距和数字的总宽度可能大于统计卡片。',
    solution:
      '数值列改为可收缩的 minmax(0,1fr)，使用 ResizeObserver 按真实可用宽度自动计算字号；达到最小字号后再横向等比收紧，并用 overflow-hidden 兜底。',
    prevention: '紧凑统计卡里的动态数字应根据容器实测宽度适配，不应依赖固定最小宽度或只按整个视口计算字号。',
    keywords: ['作品概览', '数字越界', 'AutoFitText', 'ResizeObserver', 'NovelLibraryPage'],
    updatedAt: '2026-07-14',
  },
  {
    id: 'novel-library-three-equal-summary-cards-001',
    title: '首页顶部只保留三张等宽作品卡片',
    area: '我的小说 / 顶部作品卡片',
    symptom:
      '作品概览、作品整理、最近编辑之外仍保留一张没有实际功能的扩展卡片，四张卡片还通过拖拽宽度保存不同占比，无法自然平分可用空间。',
    cause:
      '上一版为未来功能预留了第四张卡片，并沿用了四卡片可拖拽宽度模型；当扩展内容不再需要时，这套状态会继续挤占主页宽度。',
    solution:
      '删除扩展卡片、三条拖拽分隔线和持久化宽度状态，将顶部网格固定为三个 minmax(0,1fr) 等宽列，让作品概览、作品整理、最近编辑随容器宽度自动各占三分之一。',
    prevention:
      '主页顶部没有明确内容的预留卡不要长期占位；卡片数量变更时同步收敛宽度状态、分隔线和源码断言，默认使用等分自适应网格。',
    keywords: ['我的小说', '作品概览', '作品整理', '最近编辑', '扩展卡片', '三等分', 'NovelLibraryPage'],
    updatedAt: '2026-07-19',
  },
  {
    id: 'novel-library-toolbar-actions-formal-migration-001',
    title: '作品整理操作应进入正式作品列表工具栏',
    area: '我的小说与我的剧本 / 顶部概览 / 作品列表工具栏',
    symptom: '作品整理单独占用顶部信息卡片，而搜索、回收站、卡片设置、导入和新建没有形成连续的作品列表操作区。',
    cause: '早期将管理动作和概览信息并列成卡片，后续即使删除扩展卡，作品整理仍会挤占最近编辑的展示宽度。',
    solution:
      '把测试板块验证过的布局迁入正式页面：顶部改为作品概览40%、最近编辑60%；搜索框缩至156px，右侧依次平铺红色回收站、卡片设置、导入作品和青色新建作品，并删除临时测试页及入口。',
    prevention:
      '信息展示使用顶部卡片，作品级操作集中在列表工具栏；临时布局测试确认后必须同步迁入正式页并清理测试文件、入口和渲染分支。',
    keywords: ['作品整理', '作品概览', '最近编辑', '回收站', '卡片设置', '导入小说', '新建小说', 'NovelLibraryPage'],
    updatedAt: '2026-07-19',
  },
  {
    id: 'chapter-structure-audit-thinking-card-first-frame-001',
    title: '剧情审核发送后应直接显示思考卡片',
    area: '工作台 / 剧情审核 / AI输出预览',
    symptom:
      '点击剧情审核发送后，输出区先以普通正文显示“正在思考…”，收到第一段模型推理后才切换成青色思考卡片，造成明显的版式跳变。',
    cause:
      '后台任务和审核状态的 initialOutput 使用普通字符串；思考卡片渲染依赖 THINKING 标记，而该标记此前要等 reasoning 分块到达后才生成。',
    solution:
      '为剧情审核创建空的 THINKING 标记占位，任务启动和页面状态首帧都写入同一个占位内容；模型推理到达后在原卡片内更新，不再从普通正文切换布局。',
    prevention: '带专用流式容器的AI流程应让初始占位和后续分块使用同一种协议标记，避免先渲染通用文本、再切换专用组件。',
    keywords: ['剧情审核', '正在思考', 'THINKING', 'reasoning', '首帧', '布局跳变', 'useChapterReviewRequest'],
    updatedAt: '2026-07-19',
  },
  {
    id: 'workbench-setting-library-cache-width-collapse-001',
    title: '设定页拆分后应继续铺满工作区宽度',
    area: '工作台 / 设定 / 页面框架',
    symptom: '设定页的目录、设定编辑区和 AI 生成区只占据窗口左侧，右侧留下大面积空白。',
    cause:
      '为减少脑洞切换卡顿而新增的资料库缓存包装层只保留了高度，没有继承拆分前资料库根节点的横向 flex-1 和 min-w-0 约束，因此包装层按内容固有宽度收缩。',
    solution:
      '按 main 分支拆分前的自适应框架恢复缓存包装层的 min-w-0 和 flex-1，让内部左栏、弹性中栏、右栏网格重新使用工作区全部可用宽度，同时保留缓存和组件拆分。',
    prevention:
      '从横向 flex 容器中抽取或增加包装组件时，必须同步迁移原根节点的 flex-1、min-w-0 和高度约束，并用源码回归断言锁定缓存包装层。',
    keywords: ['设定页', '右侧空白', 'flex-1', 'min-w-0', '组件拆分', 'WorkbenchCreationFlowContent'],
    updatedAt: '2026-07-19',
  },
  {
    id: 'workbench-work-info-section-border-contrast-001',
    title: '作品信息中的概览和简介外框需要更明显',
    area: '工作台 / 作品信息 / 作品概览与作品简介',
    symptom: '作品信息弹窗中，“作品概览”和“作品简介”两个大区域的外框颜色过浅，在白色背景上不容易辨认区域边界。',
    cause: '两个外层 section 使用 border-gray-200，和弹窗白底及内部浅灰内容卡的明度过于接近。',
    solution:
      '仅将作品概览和作品简介两个外层 section 的边框加深为 border-slate-300，保持内部统计卡、简介内容区和弹窗外框不变。',
    prevention:
      '白底弹窗中的一级内容分区应使用比内部卡片更明确的边框层级；调整边框时用定向断言锁定作用范围，避免连带加深内部元素。',
    keywords: ['作品信息', '作品概览', '作品简介', '外框', '边框对比度', 'WorkbenchWorkInfoModal'],
    updatedAt: '2026-07-19',
  },
  {
    id: 'workbench-brainstorm-manual-serial-resequence-001',
    title: '脑洞删除后应支持手动整理连续序号',
    area: '工作台 / 脑洞 / 左侧脑洞库',
    symptom: '脑洞目录只显示名称，删除中间脑洞后无法辨认原有编号，也没有把剩余脑洞重新整理为连续编号的入口。',
    cause: '脑洞条目此前没有独立持久化序号，列表只能依赖数组位置，无法同时满足删除后保留空号和按需重新编号。',
    solution:
      '为脑洞条目增加持久化序号，左侧显示“1号 + 名称”；新脑洞沿用最大序号递增，并在回收站上方增加“脑洞排序”，按当前列表顺序将现有脑洞重排为1、2、3……。',
    prevention: '需要保留删除空号的业务编号应独立于数组下标；自动迁移旧数据，只有用户明确点击整理时才压缩编号。',
    keywords: ['脑洞库', '脑洞序号', '脑洞排序', '回收站', '连续编号', 'WorkbenchLibrarySidebar'],
    updatedAt: '2026-07-19',
  },
  {
    id: 'workbench-chapter-outline-tree-entry-stutter-001',
    title: '进入章纲时左侧导航树不应延迟出现',
    area: '工作台 / 章纲与梗概 / 左侧导航树',
    symptom: '点击进入章纲后，页面会短暂卡住，左侧卷章导航树稍后才显示；章节和正文越多越明显。',
    cause:
      '章纲和梗概资料库此前随页面切换反复挂载，每次进入都会同步读取并解析多份本地资料与展开状态；导航树渲染每个章节时还会重新从 localStorage 读取整章正文并统计字数，初始化后的状态恢复又触发多轮重复渲染。',
    solution:
      '将章纲和梗概改为与设定、脑洞一致的稳定缓存实例，仅切换可见性并只向当前页面发送工具信号；导航树直接使用随章节数据实时维护的 wordCount，不再逐章读取和扫描正文。',
    prevention:
      '高成本资料库页面切换时应保持控制器实例稳定；目录状态只能读取轻量元数据，禁止在列表渲染循环里同步读取并扫描每个文档正文。',
    keywords: ['章纲', '梗概', '左侧导航树', '卡顿', '缓存实例', 'localStorage', 'wordCount'],
    updatedAt: '2026-07-19',
  },
  {
    id: 'settings-user-and-test-category-groups-001',
    title: '软件设置应区分用户设置与测试设置',
    area: '设置 / 左侧设置分类',
    symptom: '系统、迁移、快捷键、主题、导航和默认封面入口全部平铺，无法区分正式用户功能与开发测试功能。',
    cause: '设置导航只使用单个扁平数组，没有分类数据和分组标题，主题颜色测试入口与正式用户设置混排。',
    solution:
      '新增“用户设置”和“测试设置”两个导航分类：用户设置按系统设置、数据迁移、快捷键设置、导航设置、默认封面设置排列；测试设置当前包含主题颜色，并为分类增加稳定标识。',
    prevention: '新增设置入口时必须先明确归属用户设置或测试设置，并用分组范围和顺序断言防止测试功能混入用户设置。',
    keywords: ['软件设置', '用户设置', '测试设置', '主题颜色', '设置分类', 'SettingsPage'],
    updatedAt: '2026-07-19',
  },
  {
    id: 'workbench-brainstorm-request-border-output-gap-001',
    title: '脑洞要求输入框边线和输出间距需要更清晰紧凑',
    area: '工作台 / 脑洞 / AI输出与要求输入框',
    symptom: '“请输入要求”输入框边线偏浅，并且 AI 输出框下方存在较高留白，两个连续操作区域显得分离。',
    cause: '脑洞要求输入框继承通用 neutral 灰色边线；AI 输出列表还保留20px底部内边距，与网格8px间距叠加。',
    solution: '为脑洞要求输入框增加专属深色边线，把 AI 输出列表底部内边距由20px缩至4px，使两框总间距约为12px。',
    prevention: '脑洞页专属视觉调整使用局部类覆盖；排查相邻区域间距时同时检查容器gap与子元素padding，避免重复留白。',
    keywords: ['脑洞', 'AI输出', '请输入要求', '深色边线', '底部间距', 'xy-brainstorm-ai-input'],
    updatedAt: '2026-07-19',
  },
  {
    id: 'settings-hierarchy-flattening-design-options-001',
    title: '设置页面需要减少同时可见的导航层级',
    area: '测试板块 / 设置页面扁平化方案',
    symptom: '正式设置页同时显示主页导航、设置分类导航和系统设置内部导航，横向分栏过多，内容区被多次切割。',
    cause: '统一设置页保留了各旧设置页面自己的内部导航，又在外层新增设置分类侧栏，形成重复的信息架构。',
    solution:
      '在测试板块新增四套可交互方案：合并式单侧栏、全顶部导航、卡片首页逐级进入和搜索优先设置中心，均保留用户设置与测试设置分类，但减少同时可见的导航层级。',
    prevention: '正式迁移前先在测试页比较层级、内容宽度和切换成本；确定方案后同步删除临时页面、入口和专属测试。',
    keywords: ['设置页面', '层级', '扁平化', '设计方案', '用户设置', '测试设置', 'TestCollectionPage'],
    updatedAt: '2026-07-19',
  },
  {
    id: 'novel-card-selected-cover-effect-removed-001',
    title: '首页作品卡片不再显示当前作品蓝色选中特效',
    area: '我的小说 / 作品卡片 / 封面边框',
    symptom: '当前打开的作品封面会出现深蓝边框和半透明外环，与其他小说封面不一致，容易被误认为封面图片本身存在蓝线。',
    cause: 'NovelCard 根据 currentNovelId 计算 isSelected，并为选中作品叠加 #1e71ef 边框和 ring-2 外环。',
    solution:
      '删除小说卡片的 isSelected 展示参数和条件样式，所有作品封面统一使用普通边框；当前作品状态仍保留在工作台和标签逻辑中。',
    prevention:
      '业务上的当前作品状态不应默认改变封面素材的视觉边界；如需提示当前作品，应使用不会被误认为图片内容的独立状态标识。',
    keywords: ['作品卡片', '当前作品', '选中状态', '蓝色边框', 'ring-2', 'NovelCard'],
    updatedAt: '2026-07-19',
  },
  {
    id: 'shared-ai-config-soft-card-select-001',
    title: '模型与提示词的下拉浮层需要采用轻盈悬浮卡',
    area: '共享组件 / 模型与提示词下拉菜单 / 多页面',
    symptom: '模型和提示词展开后的下拉菜单使用粗外框与拼接结构，视觉生硬；多个创作与分析页面会同时继承这套下拉样式。',
    cause: '各页面虽然复用了 CombinedAiConfigSelect，但共享组件的下拉浮层仍采用早期的粗描边拼接结构。',
    solution:
      '仅将共享组件的下拉菜单迁移为测试方案一的独立白色圆角浮层、弱描边和柔和阴影，保留原模型框与提示词框，同时保留分组、禁用、右键与管理行为。',
    prevention:
      '跨页面的模型与提示词选择必须继续复用共享组件；迁移局部视觉方案时需分别锁定触发框和下拉浮层的修改范围。',
    keywords: ['模型', '提示词', '下拉菜单', '轻盈悬浮卡', 'CombinedAiConfigSelect', '共享组件'],
    updatedAt: '2026-07-19',
  },
  {
    id: 'shared-ai-config-trigger-restoration-001',
    title: '迁移下拉方案时不应改动模型与提示词触发框',
    area: '共享组件 / 模型与提示词配置 / 多页面',
    symptom: '用户只要求采用方案一的下拉菜单，但模型框和提示词框也被替换成浅灰底板上的白色悬浮卡。',
    cause: '迁移时把测试方案的触发框和下拉浮层视为不可拆分的整体，没有限定用户要求中的“下拉框”范围。',
    solution: '恢复原有青色双栏外框、顶部标签、齿轮管理按钮和展开箭头，仅保留方案一的独立白色圆角下拉浮层。',
    prevention: '迁移测试页中的局部视觉方案前，应分别确认触发器与浮层的修改边界，并用回归断言锁定未授权区域的原样式。',
    keywords: ['模型框', '提示词框', '下拉框', '恢复', '修改范围', 'CombinedAiConfigSelect'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'novel-card-move-submenu-hover-gap-001',
    title: '作品移入分类二级菜单不应被悬停空档打断',
    area: '首页 / 作品卡片 / 移入分类菜单',
    symptom: '鼠标从“移入”菜单项横向移动到分类二级菜单时会经过一段空档，二级菜单在指针到达前消失。',
    cause: '分类菜单使用 left-full 后又增加 ml-1，一级菜单与二级菜单之间形成了4px不属于悬停容器的真空区。',
    solution: '移除外边距并让二级菜单向一级菜单方向重叠1px，建立连续的鼠标悬停通道，同时保留两层菜单原有边框。',
    prevention:
      '悬停触发的级联菜单之间不能使用真实外边距制造间隔；需要视觉分隔时使用阴影、边框或带透明悬停桥的重叠定位。',
    keywords: ['作品卡片', '移入', '分类菜单', '二级菜单', '悬停空档', 'NovelCard'],
    updatedAt: '2026-07-19',
  },
  {
    id: 'workbench-chapter-outline-cache-height-collapse-001',
    title: '章纲页面拆分后主体不能按内容高度收缩',
    area: '工作台 / 章纲 / 缓存布局层',
    symptom: '章纲目录、正文预览和右侧AI区域只占页面上半部分，下面留下大面积空白。',
    cause:
      'main分支中 WorkbenchLibraryPanel 直接作为flex子项占满工作区；组件拆分后新增的缓存包装层虽有h-full和flex-1，但自身不是flex容器，内部面板的flex-1失去伸展上下文。',
    solution: '为设定/脑洞、章纲、梗概三个资料库缓存包装层补上flex，使内部资料库面板恢复main分支的全高伸展行为。',
    prevention:
      '在flex页面中新增缓存或条件显示包装层时，必须同时传递flex、flex-1、min-h-0和min-w-0，并用章纲短内容场景锁定全高布局。',
    keywords: ['章纲', '页面空白', '缓存层', 'flex', 'min-h-0', 'WorkbenchCreationFlowContent', 'main分支'],
    updatedAt: '2026-07-19',
  },
  {
    id: 'chapter-review-bottom-safe-spacing-001',
    title: '剧情审核内容列底部需要与窗口边缘留出呼吸空间',
    area: '工作台 / 剧情审核 / 章纲与原文预览',
    symptom: '章纲、原文和AI审核列直接铺到桌面窗口最底边，视觉上像与系统任务栏连在一起，页面收尾显得突兀。',
    cause: '嵌入式剧情审核网格占满工作区全部可用高度，但没有为桌面窗口底边预留视觉安全间距。',
    solution:
      '仅在嵌入式审核、点评和润色页面的三列共享网格底部增加12px浅灰安全留白，让各列统一收住，同时保留列内滚动和旧弹窗布局。',
    prevention: '全高嵌入式桌面页面贴近窗口底边时，应检查是否需要统一的安全留白，并用范围断言确保留白不影响弹窗模式。',
    keywords: ['剧情审核', '章纲', '原文', '底部留白', '任务栏', 'pb-3', 'ChapterReviewPanel'],
    updatedAt: '2026-07-19',
  },
  {
    id: 'outline-writing-unpublished-header-height-001',
    title: '章纲与正文的未发布标题栏高度需要一致',
    area: '工作台 / 章纲与正文 / 左侧未发布目录',
    symptom: '在章纲和正文之间切换时，左侧“未发布”整行会出现可感知的上下高度变化。',
    cause: '正文未发布标题栏固定为48px，章纲标题栏单独使用42px并附带垂直内边距，两者相差6px。',
    solution: '以正文为基准，将章纲未发布标题栏统一为h-12的48px高度，并采用与正文一致的水平内边距结构。',
    prevention: '相邻工作流共用同类目录标题栏时，应复用同一固定高度规格，并用源码回归断言锁定切换前后的高度一致性。',
    keywords: ['章纲', '正文', '未发布', '标题栏高度', 'h-12', 'DETAIL_OUTLINE_SIDEBAR_HEADER_CLASS'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'settings-hierarchy-scheme-one-migrated-001',
    title: '设置页面方案一已迁入正式页并清理临时测试',
    area: '设置 / 合并式单侧栏 / 统一系统设置导航',
    symptom: '09号设置扁平化测试确认方案一后，正式设置页仍使用外层分类侧栏和系统设置内部侧栏，导航层级重复。',
    cause: '方案一只停留在测试预览，正式 SettingsPage 没有把窗口、关联设置和软件图标收进同一侧栏层级。',
    solution:
      '正式设置页改为合并式单侧栏：用户设置与测试设置分组保留，系统设置展开窗口、关联设置和软件图标子项；SystemSettingsModal 支持受控子项并隐藏重复导航，同时删除09号临时方案页、入口和渲染分支。',
    prevention:
      '设置层级方案确认后要在同一任务迁入正式页并删除临时测试入口；新增系统子项时优先复用统一侧栏的受控导航，避免再次出现嵌套重复导航。',
    keywords: ['09号测试', '方案一', '合并式单侧栏', 'SettingsPage', 'SystemSettingsModal', '临时测试清理'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'settings-hierarchy-scheme-two-test-restored-001',
    title: '设置页面方案二需要保留在测试板块对比',
    area: '测试板块 / 设置页面 / 全顶部导航方案',
    symptom: '方案一已经迁入正式设置页后，用户希望继续对比方案二，但原来的设置层级测试入口已被清理。',
    cause: '方案选型迁移时只保留了正式代码，删除了包含方案二预览的临时测试页面，后续无法直接回看另一种层级。',
    solution:
      '保留正式设置页方案一代码不变，恢复独立的09号方案二测试页：顶部横向显示用户设置，系统子项放在内容标题右侧，并重新注册到测试集合末尾。',
    prevention:
      '用户要求保留对比方案时，测试页面应与正式实现分离；正式页采用已选方案，未选方案保留在测试板块，便于回退前继续比较。',
    keywords: ['09号测试', '方案二', '全顶部导航', '测试板块', 'SettingsHierarchyDesignTestPage'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'settings-hierarchy-scheme-two-migrated-001',
    title: '08号设置方案二已迁入正式页并保留方案一备份',
    area: '设置 / 全顶部导航 / 方案迁移',
    symptom: '08号测试确认全顶部导航更符合设置页使用习惯，但正式页仍显示方案一的合并式侧栏。',
    cause: '测试页与正式设置页使用两套布局，方案二的顶部用户设置导航和系统子导航没有接入真实设置内容。',
    solution:
      '正式 SettingsPage 改为方案二：用户设置和测试设置通过顶部导航切换，系统子项放在内容标题右侧；将方案一完整代码保存在 SettingsPageSchemeOneBackup.tsx，便于随时恢复。',
    prevention:
      '设置方案切换时要保留已验证方案的可恢复代码，并让顶部导航、系统子导航和真实设置内容共用同一套 section 状态。',
    keywords: ['08号测试', '方案二', '全顶部导航', 'SettingsPage', 'SettingsPageSchemeOneBackup'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'novel-card-menu-design-08-migrated-001',
    title: '08 test: migrate the novel card menu design',
    area: 'Novel library / novel card / more menu',
    symptom: 'The confirmed menu hierarchy and connected category submenu existed only in the 08 test page.',
    cause:
      'NovelCard still rendered a compact single-level menu, so the tested hierarchy was not visible in the real card.',
    solution:
      'Moved the update and category metadata, section dividers, connected category submenu, and recycle action styling into NovelCard, then removed the temporary 08 test page.',
    prevention:
      'When a card-menu prototype is confirmed, verify its real callbacks in NovelCard and remove the temporary collection entry in the same change.',
    keywords: ['08 test', 'novel card', 'more menu', 'move category', 'submenu', 'NovelCard'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'chapter-review-rerun-stale-revised-draft-001',
    title: '再次审核或润色时不应继续显示上一次已应用正文',
    area: '工作台 / 文本审核与润色 / AI重复生成',
    symptom: '第一次应用审核修改后再次发送AI请求，新的审核结果可能始终不显示，预览仍停留在上一次已应用正文。',
    cause:
      '应用修改会写入reviewRevisedDraft，而新请求开始时只替换output和任务信息，没有清空旧草稿；预览又优先读取非空草稿。',
    solution:
      '新增统一的请求开始状态转换，在写入本次输出、日志和任务编号时同步清空revisedDraft，让新AI输出重新接管预览。',
    prevention: '审核和润色的重复生成测试必须覆盖“应用旧结果后再次发送”场景，并断言请求开始时旧草稿已清空。',
    keywords: ['文本审核', '润色', '再次生成', '旧草稿', 'reviewRevisedDraft', 'beginReviewModeRequest'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'settings-system-subnav-text-only-buttons-001',
    title: '系统设置子导航按钮应保持仅文字形式',
    area: '设置 / 系统设置子导航 / 按钮规范',
    symptom: '窗口、关联设置和软件图标三个新子导航同时显示图标与文字，不符合项目新增按钮默认仅图标或仅文字的约定。',
    cause: '从测试方案迁移顶部子导航时直接携带了每个标签的图标配置，没有按正式页面按钮规范收敛。',
    solution: '删除系统子导航的图标配置与渲染，只保留清晰的文字标签和当前页状态。',
    prevention: '新增导航按钮时通过源码门禁检查图标与文字是否同时出现；没有用户明确要求时默认选择一种表达形式。',
    keywords: ['系统设置', '子导航', '仅文字按钮', '按钮规范', 'SettingsPage', 'SystemTabButtons'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'settings-wide-action-rows-waste-space-001',
    title: '设置项不应使用按钮远离说明的全宽操作行',
    area: '设置 / 系统设置 / 窗口与关联设置',
    symptom: '设置项文字集中在左侧、操作按钮贴在最右侧，中间出现大面积空白，页面松散且对应关系不够直观。',
    cause: '短设置项沿用了全宽单行的justify-between布局，内容区越宽，说明和操作之间的无效距离越大。',
    solution:
      '将窗口和关联设置改为宽屏两列、窄屏单列的紧凑信息卡，并把标题、说明、尺寸状态和操作收进同一卡片；同时压缩顶部导航、标题栏和内容区间距。',
    prevention: '短设置项优先使用有最大宽度的紧凑卡片或短行布局，不再默认用全宽两端对齐承载说明与操作。',
    keywords: ['设置', '窗口大小', '空间浪费', '紧凑卡片', '两列布局', 'SystemSettingsCompactSections'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'data-migration-actions-match-new-novel-button-001',
    title: '数据迁移按钮应匹配新建小说的青色样式',
    area: '设置 / 数据迁移 / 导入导出按钮',
    symptom: '导出全局备份和导入全局备份使用白底描边按钮并携带图标，与新建小说及软件主要操作的青色样式不一致。',
    cause: '数据迁移操作沿用了旧工具栏的图标按钮样式，没有复用当前新建小说按钮的尺寸、圆角和品牌色。',
    solution: '删除两个按钮中的图标，改用与新建小说一致的40px高度、10px圆角、青色背景、白色粗体文字和悬停色，并保留禁用状态。',
    prevention: '设置页主要操作应通过回归断言与新建小说按钮共享同一核心样式字符串，同时断言不再导入或渲染对应图标。',
    keywords: ['数据迁移', '导出全局备份', '导入全局备份', '新建小说', '青色按钮', '仅文字按钮'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'navigation-settings-left-work-area-001',
    title: '导航设置编辑区应收窄并保持左对齐',
    area: '设置 / 导航设置 / 编辑区宽度',
    symptom: '导航设置列表和操作按钮横跨整个页面，无法在右侧为后续其他功能预留独立空间。',
    cause: '嵌入式导航设置容器使用w-full占满设置内容区，没有工作区最大宽度。',
    solution: '将嵌入式导航编辑区限制为左对齐的960px最大宽度，窄屏继续使用100%宽度；右侧保持纯空白，不渲染占位内容。',
    prevention: '导航设置布局测试必须断言嵌入工作区包含max-w-[960px]且不包含mx-auto，同时确认容器后没有额外占位节点。',
    keywords: ['导航设置', '左对齐', '960px', '预留空间', 'NavSettingsModal'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'retire-text-overrides-and-consolidate-direct-routes-001',
    title: '废弃文案修改并收拢重复直达路由',
    area: '应用路由 / 文案修改 / 资料库 / 数据迁移',
    symptom: '文案修改已不再需要，但管理页、全局文字替换层、存储和快捷键仍完整存在；概念库与数据迁移同时保留统一页面入口和重复直达页面。',
    cause: '历史功能隐藏正式导航后没有同步移除运行时主体，概念库和数据库设置也继续作为独立正式路由注册。',
    solution: '删除文案修改页面、全局替换层、存储、快捷键和正式路由；取消概念库、数据库设置的独立页面注册，并将旧地址分别重定向到资料库和设置的数据迁移分区。',
    prevention: '退休功能必须同时清理页面、全局挂载、状态存储、快捷键和路由；嵌入统一页面的功能只保留一个正式注册，并通过退休代码门禁阻止旧组件重新进入运行时。',
    keywords: ['文案修改', '重复路由', '概念库', '数据迁移', 'TextOverrideLayer', 'routeRegistry'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'shortcut-settings-five-column-grid-001',
    title: '快捷键设置宽屏下一行应显示五项',
    area: '设置 / 快捷键设置 / 卡片网格',
    symptom: '快捷键设置在宽屏下一行只能显示四项，没有充分利用横向空间。',
    cause: '快捷键卡片网格的宽屏断点固定为xl:grid-cols-4。',
    solution: '将快捷键卡片网格的宽屏列数改为xl:grid-cols-5，同时保留单列、两列和三列的响应式断点。',
    prevention: '快捷键设置布局测试应渲染真实页面并断言宽屏网格保持五列，避免后续样式调整退回四列。',
    keywords: ['快捷键设置', '五列', '宽屏', '响应式网格', 'ShortcutSettingsModal'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'settings-data-migration-remove-repeated-title-001',
    title: '数据迁移页不应重复显示全局数据迁移标题',
    area: '设置 / 数据迁移 / 顶部操作栏',
    symptom: '顶部主标签已经显示数据迁移，内容区仍额外显示全局数据迁移标题和迁移说明，造成重复层级并占用纵向空间。',
    cause: '数据迁移页面保留了原独立页面的标题栏结构，嵌入统一设置页后没有隐藏左侧标题说明。',
    solution: '删除标题栏左侧的全局数据迁移标题与说明，仅保留右侧导出全局备份、导入全局备份按钮及原有处理逻辑。',
    prevention: '独立页面嵌入统一标签页时应检查重复标题；删除展示结构时必须通过回归断言锁定关键操作按钮、事件处理函数和导入文件控件仍然存在。',
    keywords: ['设置', '数据迁移', '重复标题', '导出全局备份', '导入全局备份', 'DbSettingsPage'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'settings-four-column-left-aligned-grid-001',
    title: '设置卡片应使用四列左对齐网格',
    area: '设置 / 系统设置 / 设置卡片排列',
    symptom: '宽屏下设置卡片一行只能显示两个，并且受最大宽度与自动外边距影响整组居中；只有两个设置时没有占据前两个列位。',
    cause: '窗口和关联设置共用的卡片容器固定为两列，并设置了mx-auto与1080px最大宽度，导致列数不足且剩余卡片无法从页面左侧开始排列。',
    solution: '统一改为宽屏四列、窄屏两列或单列的响应式网格，移除居中和最大宽度限制；卡片使用等高布局，底部状态与按钮通过mt-auto对齐。',
    prevention: '设置卡片容器必须锁定四列宽屏门禁，并断言不再出现mx-auto或固定最大宽度；不足四项时依靠标准网格自动占据前几个列位。',
    keywords: ['设置', '四列', '左对齐', '设置卡片', 'SystemSettingsCompactSections', 'grid-cols-4'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'settings-remove-duplicate-section-banner-001',
    title: '设置页不应重复显示当前主标签标题块',
    area: '设置 / 顶部主标签 / 系统设置子标签',
    symptom: '顶部已经显示系统设置、数据迁移、快捷键设置等主标签，正文上方仍重复显示同名大标题和说明，占用高度并造成重复层级；系统设置子标签又被推到该重复标题行右侧。',
    cause: '统一设置页在顶部标签导航之外继续渲染旧的 section banner，并把系统设置子导航和快捷键恢复操作都挂载在该 banner 中。',
    solution: '删除重复 section banner；把窗口、关联设置、软件图标子标签移到主标签行正下方，并把快捷键恢复默认操作收进主标签行右侧。',
    prevention: '页面已经使用主标签表达当前分区时，不再额外渲染同名标题块；存在二级标签时应紧邻主标签下方，并用源码回归断言锁定顺序。',
    keywords: ['设置', '重复标题', '系统设置', '二级标签', '窗口', '关联设置', '软件图标', 'SettingsPage'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'replace-body-short-output-warning-001',
    title: '替换正文前应提醒输出字数过少',
    area: '工作台 / 正文 / AI输出替换正文',
    symptom:
      'AI输出很短时点击替换正文会直接覆盖当前章节，用户可能在没有注意字数的情况下把完整正文替换成不足两千字的内容。',
    cause: '替换正文动作只检查输出是否为空，没有在覆盖前比较输出字数，也没有提供可调整的提醒阈值。',
    solution:
      '默认在准备替换的正文少于2000字时弹出统一风格确认窗，并在正文右上角的作品编辑器设定中增加可配置阈值；阈值设为0可关闭提醒。',
    prevention:
      '所有会整段覆盖正文的入口都应先执行统一字数门禁，并通过回归测试覆盖低于阈值、等于阈值和用户确认继续替换三种情况。',
    keywords: ['正文', '替换正文', '字数提醒', '2000字', '确认弹窗', 'WorkbenchReplaceBodyButton'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'published-chapter-retract-action-color-001',
    title: '已发布章节的撤回按钮应与发布按钮使用相同操作色',
    area: '工作台 / 正文 / 已发布章节列表',
    symptom: '已发布章节悬停时显示的撤回按钮是灰色，而未发布章节的发布按钮是青色，两侧对应操作的视觉风格不一致。',
    cause: '撤回按钮保留了旧的gray背景类，没有复用发布按钮当前使用的青色操作色和悬停色。',
    solution: '将撤回按钮改为与发布按钮一致的#08AACE背景和#0798b8悬停色，保留原有位置、尺寸和撤回逻辑。',
    prevention: '成对出现的发布与撤回操作应通过回归断言锁定相同的操作色，避免单侧样式更新后再次分化。',
    keywords: ['正文', '已发布', '撤回', '发布', '按钮颜色', 'PublishedSidebar'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'chapter-review-thinking-auto-collapse-001',
    title: '剧情审核开始输出正文后应自动折叠思考过程',
    area: '工作台 / 剧情审核 / AI输出预览',
    symptom: '模型已经开始输出真正的审核结果后，已思考卡片仍完整展开，占用右侧输出区较大高度。',
    cause: '思考卡片只负责显示推理内容，没有根据正式答案是否出现切换展开状态，也没有提供手动折叠控件。',
    solution: '思考期间保持展开；检测到首段正式答案后自动收成一行，并允许用户点击标题自行展开或再次折叠。',
    prevention: '思考流式展示的回归测试应覆盖正式答案出现时自动折叠，以及用户手动展开后后续分块不再强制关闭。',
    keywords: ['剧情审核', '已思考', '自动折叠', '正式输出', '流式输出', 'renderAiThinkingContent'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'default-cover-two-column-dense-layout-001',
    title: '默认封面与自定义上传应分区并紧凑排列',
    area: '设置 / 默认封面设置 / 封面布局',
    symptom: '自定义上传与内置封面纵向堆叠，普通封面排在简约封面之前，内置封面间距过大并浪费横向空间。',
    cause: '页面使用单列分区，自定义上传占满整行，内置封面分组顺序和网格间距仍沿用旧布局。',
    solution: '宽屏改为左右两栏，左侧先显示简约封面再显示普通封面，右侧独立放置自定义上传；内置封面改为左对齐的紧凑自适应网格并将间距压缩到8px。',
    prevention: '默认封面设置的回归测试应锁定分组顺序、宽屏两栏结构、自定义上传区域和紧凑网格间距。',
    keywords: ['默认封面设置', '简约封面', '普通封面', '自定义上传', '两栏布局', '紧凑间距'],
    updatedAt: '2026-07-20',
  },
  {
    id: 'default-cover-current-badge-without-selection-ring-001',
    title: '默认封面选中状态不应重复显示外框',
    area: '设置 / 默认封面设置 / 选中状态',
    symptom: '当前使用的封面同时显示右上角状态标识和青色描边光圈，选中反馈重复且外框显得突兀。',
    cause: '封面卡片沿用了描边光圈选中态，同时又新增了当前使用状态标识。',
    solution: '移除内置封面和自定义封面的青色选中描边及光圈，仅保留当前使用标识、基础细边框和悬停反馈。',
    prevention: '封面设置回归测试应断言选中描边光圈类不再出现，避免与当前使用标识重复表达状态。',
    keywords: ['默认封面', '当前使用', '选中外框', '描边', '光圈'],
    updatedAt: '2026-07-20',
  },
];
