import type { ErrorLogEntry } from './errorLogEntryTypes';

export const defaultEntriesPart40: ErrorLogEntry[] = [
  {
    id: 'ai-request-log-collapsed-section-keeps-height-001',
    title: '输出日志折叠分组时应收起整个框',
    area: '作品工作台 / 设定输出日志 / 提示词分组折叠',
    symptom: '在设定输出日志中折叠“提示词”后，正文内容消失了，但外层大框仍然占满右侧区域，看起来只是清空内容而不是折叠。',
    cause: 'AiRequestLogGroups 在单个分组 fillSingleGroup 场景下无论是否 collapsed 都给 section 保留 flex-1 填充高度，折叠状态只移除了内容节点，没有取消外框填充。',
    solution: '将 shouldFillGroup 调整为单组日志也必须在未折叠时才填充高度，折叠后只保留标题行高度。',
    prevention: '共享输出日志测试锁定 shouldFillSingleGroup 必须同时判断 !collapsed，设定日志和其他复用日志以后不会再只清空内容而保留空框。',
    keywords: ['输出日志', '提示词', '折叠', '空框', 'AiRequestLogGroups', 'fillSingleGroup'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'locked-default-setting-hover-help-missing-001',
    title: '锁定内置设定悬浮时应说明无法删除',
    area: '作品工作台 / 设定页面 / 左侧设定树与所属分组禁用框',
    symptom: '内置设定已经被锁定，右键删除和改名等操作会被拦截，但鼠标移到锁定设定或禁用的所属分组上没有说明原因。',
    cause: '删除限制集中在 isLockedDefaultSettingEntry 和控制器逻辑中，设定树叶子节点、旧资料库侧栏和 WorkbenchHeaderSelect 没有透传锁定提示 title。',
    solution: '给锁定内置设定条目和禁用的所属分组下拉统一增加 title="内置设定，无法删除"，并让 WorkbenchHeaderSelect 支持把 title 同时挂到外框和 select 上。',
    prevention: '组件测试和源码迁移测试同时锁定正式设定树、旧资料库侧栏、WorkbenchHeaderSelect 与设定编辑器的锁定提示，避免后续只保留删除拦截而丢失用户可见解释。',
    keywords: ['内置设定', '锁定设定', '无法删除', '悬浮提示', '所属分组', '设定树'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'setting-editor-top-clearance-vs-field-gap-001',
    title: '设定页顶部留白不应靠拉大名称行到字段区距离实现',
    area: '作品工作台 / 正式设定页 / 设定名与结构化字段间距',
    symptom: '用户希望加大切换设定行下方到设定名行之间的红框高度，但实际被加大的是设定名和能力来源等字段卡片之间的距离。',
    cause: '上次将顶部舒适间距拆到了 header 的 pb-4 和内容区 pt-4，导致名称行与字段区之间额外增加 32px，而顶部红框只保留外层 pt-6。',
    solution: '把正式设定编辑器外层顶部间距改为 pt-8，并将 header 底部与内容区顶部收回到 pb-1、pt-2，让红框区域加高而字段区保持紧凑。',
    prevention: '回归测试分别锁定外层 pt-8、header pb-1 和内容区 pt-2，避免以后把顶部留白误加到设定名与字段卡片之间。',
    keywords: ['设定页', '顶部留白', '设定名', '能力来源', '字段间距', '红框高度'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'setting-status-panel-small-text-bottom-action-001',
    title: '设定状态面板字号和主操作按钮位置应符合右侧面板阅读习惯',
    area: '作品工作台 / 正式设定页 / 更新状态右侧面板',
    symptom: '待确认、历史状态、更新依据和字段更新规则整体字号偏小；“分析正文状态变化”按钮跟随内容流停在中部，页面底部留出大量空白。',
    cause: '状态面板根容器整体作为滚动区，按钮放在滚动内容末尾；统计块、标题、空状态和规则行沿用 10px 到 12px 的紧凑测试样式。',
    solution: '将状态面板改为 flex 纵向布局：中间内容区单独滚动，底部主按钮放入固定 footer；统计块、标题、空状态、依据卡片和规则行统一放大字号、圆角和间距。',
    prevention: '正式迁移回归测试锁定状态面板根容器、滚动内容区、底部固定操作区、14px 主按钮和放大后的统计块字号，避免再次退回小字和中部按钮。',
    keywords: ['设定状态', '字号太小', '分析正文状态变化', '底部按钮', '更新依据', '字段更新规则'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'setting-status-auto-match-banner-noise-001',
    title: '设定状态面板不应显示自动匹配说明横幅',
    area: '作品工作台 / 正式设定页 / 更新状态右侧面板',
    symptom: '更新状态面板顶部显示“已自动匹配：主角金手指/优势。状态分析不要求预先手动关联。”，占用空间且用户已明确要求删除。',
    cause: '状态面板在每个已选设定上都渲染自动匹配说明横幅，但当前正式流程已经通过左侧选中项和面板内容表达范围，不需要额外提示。',
    solution: '删除 WorkbenchSettingStatusPanel 顶部自动匹配横幅，保留待确认、历史变化、更新依据和分析正文状态变化入口。',
    prevention: '正式迁移回归测试锁定状态面板源码不再包含“已自动匹配”和“状态分析不要求预先手动关联”文案，避免提示块回归。',
    keywords: ['设定状态', '自动匹配', '主角金手指', '提示横幅', '更新状态', '删除'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'role-survival-status-tag-select-removed-001',
    title: '人物生存状态不应额外显示状态标签下拉',
    area: '作品工作台 / 人物设定 / 生存状态控件',
    symptom: '生存状态右侧额外出现“状态标签”输入框式下拉，占用顶部栏空间，并和左侧存活/死亡分段按钮表达重复。',
    cause: '上一版常见软件参考方案同时保留了分段按钮和状态标签下拉，两者都写入同一个 lifeStatus，形成重复功能。',
    solution: '删除 WorkbenchSurvivalStatusToggle 里的状态标签 label/select，只保留左侧生存状态分段按钮；测试页对比样本和生存状态方案页同步移除该控件。',
    prevention: '组件、人物编辑器、集成用例和测试页回归测试均断言状态标签 combobox 不再渲染，避免该重复入口回归。',
    keywords: ['人物设定', '生存状态', '状态标签', '下拉', '存活', '死亡', '删除'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'setting-tree-third-level-connector-tail-001',
    title: '设定树三级导线应保留横线并去掉末尾竖线尾巴',
    area: '作品工作台 / 设定页面 / 左侧设定树导航',
    symptom: '三级设定左侧横向连接线消失，同时最后一个三级设定下面仍残留一段竖线尾巴；用户实际只要求删除末尾凸出的竖线段。',
    cause: '导线由三级列表父容器统一绘制整条竖线，无法根据最后一个三级条目截断；三级条目本身没有独立横向连接线。',
    solution: '改为每个三级条目自己渲染竖线段和横线，非最后一项竖线继续向下，最后一项竖线只到横线位置。',
    prevention: '组件测试锁定三级条目横向连接线存在，并锁定最后一项使用 bottom-1/2 截断，避免再次把横线删掉或恢复整条尾线。',
    keywords: ['设定树', '三级设定', '导线', '横线', '竖线尾巴', '导航'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'setting-field-content-typography-unified-001',
    title: '设定字段正文应和名称输入内容使用同一套字体层级',
    area: '作品工作台 / 设定页面 / 结构化字段与人物字段',
    symptom: '区域名输入框里的内容和区域概况、危险来源等字段框正文的字号、字重和颜色不同，视觉上像两套不同表单。',
    cause: '顶部名称字段使用 text-base、font-medium、text-slate-950；结构化设定字段正文仍沿用 text-sm、text-gray-700，人物字段正文也沿用 text-sm、text-slate-700。',
    solution: '新增统一字段正文类，正式设定页所有结构化字段、非结构化设定内容、空状态预览以及人物设定字段统一使用 text-base、font-medium、leading-8、text-slate-950；占位文字仍保留浅灰。',
    prevention: '正式结构化设定一致性测试锁定 SETTING_FIELD_CONTENT_CLASS 和 ROLE_FIELD_CONTENT_CLASS，并禁止旧 text-sm/text-gray-700 字段正文类回归。',
    keywords: ['设定页面', '字段正文', '区域名', '区域概况', '字体统一', '人物设定'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'setting-status-panel-history-section-removed-001',
    title: '更新状态面板不应再展示历史状态区块',
    area: '作品工作台 / 设定页面 / 更新状态右侧面板',
    symptom: '更新状态面板中显示“历史状态”和“当前字段暂无历史变化”空框，占用右侧空间且用户要求删除。',
    cause: '面板在待确认更新下方固定渲染历史状态列表，即使当前字段没有历史变化也会显示空状态。',
    solution: '删除历史状态展示区块和顶部历史变化计数，只保留待确认更新、更新依据、字段更新规则和底部分析按钮；底层 statusHistory 数据继续保留给字段记录弹窗和确认记录使用。',
    prevention: '状态面板测试和正式迁移测试断言历史状态、历史变化和当前字段暂无历史变化文案不再出现在 WorkbenchSettingStatusPanel。',
    keywords: ['更新状态', '历史状态', '历史变化', '右侧面板', '删除', '空状态'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'workbench-navigation-group-color-unified-001',
    title: '工作台各导航分组底色应统一为作品设定色',
    area: '作品工作台 / 左侧导航 / 分组与卷目录',
    symptom: '作品设定、章纲第一卷、正文第一卷以及其他库导航分组使用了不同深浅的青色，用户要求统一为作品设定的 #CDEFF6。',
    cause: '设定树一级分组、设定树二级分组、工作台库导航共用常量、章纲编辑器导航常量和正文/已发布卷导航本地常量分别维护颜色，部分仍沿用旧的 xy-flow-group-bg 或更浅的 #E6F8FC。',
    solution: '将工作台库导航分组、章纲编辑器分组、正文卷分组、已发布正文卷分组和设定树二级分组统一改为 border-[#AEE7F1] bg-[#CDEFF6] hover:bg-[#BFEAF3]，保留原有尺寸、字号、图标和计数样式。',
    prevention: '源码回归测试锁定共享分组常量、正文卷本地常量和设定树二级分组必须包含 #CDEFF6，避免以后新增或迁移导航时回到旧色。',
    keywords: ['导航分组', '作品设定', '章纲', '正文', '第一卷', '#CDEFF6', '分组颜色统一'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'setting-tree-second-level-color-step-001',
    title: '设定树二级分组颜色应介于一级和三级选中之间',
    area: '作品工作台 / 正式设定页 / 左侧设定树层级颜色',
    symptom: '作品设定和核心设定使用同一个 #CDEFF6 底色，二级分组失去层级区分，看起来和一级分组同级。',
    cause: '上次统一导航分组底色时，把正式设定树二级分组也同步成一级分组色，没有保留“作品设定 -> 核心设定 -> 基础设定”的由深到浅层级。',
    solution: '保留一级作品设定 #CDEFF6，将二级核心设定改为中间色 #DDF5FA，并使用 #D2F0F7 作为 hover；三级选中仍保留更浅的 #EAF9FD。',
    prevention: '正式设定树回归测试同时锁定一级 #CDEFF6、二级 #DDF5FA 和三级选中 #EAF9FD，避免以后再把二级和一级统一成同色。',
    keywords: ['设定树', '作品设定', '核心设定', '基础设定', '层级颜色', '#DDF5FA'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'workbench-shared-left-nav-width-published-sidebar-001',
    title: '导航宽度统一应同步已发布正文侧栏',
    area: '作品工作台 / 章节编辑器 / 已发布正文侧栏',
    symptom: '打开“导航宽度统一”后，正文目录和资料库等导航会跟随共享宽度，但已发布正文侧栏仍保留自己的独立宽度，看起来像开关没有生效。',
    cause: '共享左侧导航宽度最初只接入了正文目录、资料库和状态类面板，已发布正文侧栏仍只读写本地宽度键，没有读写共享宽度。',
    solution: '让已发布正文侧栏在统一模式下直接读取共享左侧导航宽度，并在拖拽提交时写回同一共享宽度键；取消统一时再恢复自己的本地宽度键。',
    prevention: '回归测试同时覆盖正文目录、资料库、状态页和已发布正文侧栏，确认统一开关打开后所有左侧导航都读同一宽度。',
    keywords: ['导航宽度统一', '已发布正文', '共享宽度', '左侧导航', '宽度同步'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'setting-field-content-line-height-match-15-test-001',
    title: '设定页正文行高应与15号测试保持一致',
    area: '作品工作台 / 正式设定页 / 嵌字框正文',
    symptom: '正式设定页里时代背景、世界格局、社会秩序等框内正文看起来比15号测试更松散，行高偏大，和测试里红框文字的密度不一致。',
    cause: '正式设定页的统一正文类仍使用 leading-8，而15号测试里的正文对比样式是 leading-7 的更紧凑版本。',
    solution: '将正式设定页的 SETTING_FIELD_CONTENT_CLASS 改为 text-base font-medium leading-7 text-slate-950，并保持人物页正文样式不变。',
    prevention: '正式设定页结构化正文回归测试锁定 leading-7，禁止把设定页正文类退回 leading-8 或 text-sm/text-gray-700。',
    keywords: ['设定页', '时代背景', '世界格局', '社会秩序', 'leading-7', '15号测试'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'role-survival-status-compact-label-removed-001',
    title: '人物生存状态切换不应显示额外标题',
    area: '作品工作台 / 人物设定 / 生存状态切换',
    symptom: '生存状态切换控件顶部显示“生存状态”四个字，占用空间且和存活/死亡两个状态按钮重复；圆点和状态文字偏小，识别性不足。',
    cause: '组件沿用嵌入边框标题模式渲染可见 label，同时按钮仍使用 text-xs 和 6px 圆点，和当前人物设定顶部控件的视觉重量不匹配。',
    solution: '删除可见“生存状态”标题，仅保留 aria-label 作为无障碍名称；将状态按钮文字放大到 text-sm，圆点放大到 10px，并适当增加图文间距。',
    prevention: '组件测试锁定控件内不再出现可见“生存状态”，并断言存活/死亡按钮使用 text-sm 与 h-2.5/w-2.5 圆点。',
    keywords: ['人物设定', '生存状态', '存活', '死亡', '圆点', '标题删除', '字号放大'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'work-setting-create-title-and-placeholder-typography-001',
    title: '作品设定新建条目不应默认命名为新建大纲',
    area: '作品工作台 / 正式设定页 / 新建设定与结构化字段占位字',
    symptom: '在作品设定分组点击新建设定或从空编辑区直接输入时，新条目默认标题显示为“新建大纲”；故事类型、核心创意等结构化字段占位字也比设定名“基础设定”的字重弱，视觉层级不一致。',
    cause: '设定创建存在多条路径：addSetting、createEditableSettingEntry、通用 addEntry 和空编辑区“保存为新条目”曾各自按当前底层 tab 拼接默认标题，而作品设定底层 tab 名仍可能是“大纲”；结构化字段内容类只给占位字设置 font-semibold，没有沿用嵌入标题的 font-black/leading-6 规格。',
    solution: '将作品设定的空标题默认值统一为“新建设定”，角色保留“新建角色”，其他 tab 才继续按 tab 名拼接；新增统一默认标题函数供通用新增、设定新增和空编辑区保存路径共用；正式设定编辑器的 placeholder 改为 font-black、leading-6、text-slate-400，使灰色占位字与设定名输入内容保持同字号同字重。',
    prevention: '回归测试锁定空预览自动创建条目的标题为“新建设定”，源码搜索确认正式运行路径不再直接用 activeTab 拼出作品设定默认名，并锁定 SETTING_FIELD_CONTENT_CLASS 的 placeholder 字重和行高，避免作品设定再次漏出“新建大纲”或占位字回退为轻字重。',
    keywords: ['作品设定', '新建设定', '新建大纲', '占位字', '基础设定', 'placeholder', 'font-black'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'role-protagonist-field-layout-autosize-001',
    title: '男主角人物设定字段应按内容长短重排并自动增高',
    area: '作品工作台 / 人物设定 / 男主角基础与状态字段',
    symptom: '人物设定字段按旧的两列分组平均铺开，称号外号、外貌等短内容字段占用过大，文本回车后只能在固定高度框内滚动，同行字段高度也不一致。',
    cause: '角色编辑器沿用固定 min-height 的分组渲染，没有按字段内容预期长度定义行布局，也没有根据 textarea scrollHeight 同步调整字段框高度。',
    solution: '将男主角字段重排为六行：顶部身份行不变，第二行外貌、性格、称号外号别称三等分且更矮，其余字段按两列成对排列；字段输入区按 2 至 10 行自动调整高度，超过 10 行后启用滚动，同一 CSS grid 行按最高字段同步拉齐。',
    prevention: '角色编辑器源码回归测试锁定字段行顺序、三列/两列布局、10 行高度上限和自动高度同步逻辑，避免以后恢复成固定高度或旧分组顺序。',
    keywords: ['人物设定', '男主角', '字段排序', '性格', '自动高度', 'textarea', '十行上限'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'structured-setting-card-bottom-gap-match-top-001',
    title: '结构化设定字段框正文到上下边线的间隔应一致',
    area: '作品工作台 / 正式设定页 / 结构化字段黑框',
    symptom: '世界格局等结构化字段框内，正文距离下边线的留白明显大于距离上边线的留白，长段文字接近填满时视觉上像底部多出一块空行。',
    cause: '正式结构化字段卡片使用 pt-2 但 pb-4，且固定最小高度 172px；上边距和下边距不一致，导致文字底部留白比顶部更大。',
    solution: '将结构化字段卡片统一改为 pt-2/pb-2，并把最小高度从 172px 收敛到 158px，使正文到上边线和下边线的视觉间隔按顶部间隔对齐。',
    prevention: '结构化字段正式迁移测试锁定 SETTING_FIELD_CARD_CLASS 的 min-h-[158px]、pb-2、pt-2，避免以后恢复成底部更厚的 pb-4。',
    keywords: ['设定页', '结构化字段', '世界格局', '上下间距', '黑框', 'pb-2', 'min-h-158'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'role-protagonist-field-textarea-grow-blocked-by-flex-1-001',
    title: '男主角设定框内容增多时不应被 flex-1 锁死高度',
    area: '作品工作台 / 人物设定 / 男主角字段自动增高',
    symptom: '人物设定里的长字段已经写到六行，但字段框仍保持和短字段相同的固定高度，没有继续向下增长。用户以为自动增高失效了。',
    cause: 'RoleAutoSizeTextarea 虽然会根据 scrollHeight 计算高度，但 textarea 同时保留了 flex-1，放在 flex-col 卡片里时会把内容高度压回可伸缩布局，导致视觉上像被锁死。',
    solution: '移除 RoleAutoSizeTextarea 的 flex-1，让高度完全由 scrollHeight 和行数上限驱动；保留 minHeight/maxHeight 和 overflowY 逻辑，使 2 至 10 行范围内可以随内容正常增高。',
    prevention: '角色编辑器回归测试锁定 textarea 不再包含 flex-1，并验证 scrollHeight 增大时 textarea style.height 会同步变高。',
    keywords: ['人物设定', '自动增高', 'flex-1', 'textarea', '六行', 'height', 'scrollHeight'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'brainstorm-create-prompt-modal-height-typography-001',
    title: '创建提示词弹窗不应过高且文字不应偏小',
    area: '作品工作台 / 脑洞 / 提示词管理 / 创建提示词弹窗',
    symptom: '创建提示词弹窗打开后高度接近整屏，左侧表单和右侧提示词内容文字偏小，用户需要在很高的弹窗里查看和编辑内容。',
    cause: 'BrainstormPromptEditModal 固定使用 h-[min(820px,92vh)]，内容编辑区最小高度为 260px，同时表单输入和按钮仍沿用 text-sm，导致弹窗体量大但正文识别性不足。',
    solution: '将创建/编辑提示词弹窗高度收敛到 h-[min(620px,78vh)]，内容编辑区最小高度降到 160px，并把 storageId 切到 brainstorm_prompt_editor_compact_v2，避免旧的拖拽尺寸记忆继续覆盖新版默认高度；外层 padding 和底部按钮区收紧，标题、输入框、说明框、正文框和按钮字号提升到 text-lg/text-base 层级。',
    prevention: '新增 BrainstormPromptEditModal 组件测试锁定创建弹窗高度、标题字号、compact_v2 尺寸记忆 key 和三个输入区域的 text-base/leading-7 样式，避免后续再恢复成过高小字版本。',
    keywords: ['创建提示词', '提示词管理', '脑洞', '弹窗高度', '字号', 'text-base', 'h-620', 'storageId'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'post-audit-status-update-duplicate-evidence-action-001',
    title: '审核后状态更新不应在待确认卡片里重复放更新依据按钮',
    area: '测试集合 / 审核后状态更新工作台 / 右侧待确认更新',
    symptom: '每条待确认更新卡片里已有“更新依据”按钮，下方又有独立的“2. 更新依据”区块，两个入口重复，用户不确定是否都需要保留。',
    cause: '上一版为了让每条卡片能直接跳原文，把“更新依据”放进卡片操作区；后来又新增了独立依据区，导致同一动作在上下两处同时出现。',
    solution: '删除待确认卡片里的“更新依据”按钮，卡片点击只负责切换当前更新项；下方“更新依据”区集中展示理由，并保留“查看原文第 N 段”作为唯一跳原文入口。',
    prevention: '状态更新测试锁定待确认卡片内不再存在名为“更新依据”的按钮，并验证点击卡片后可通过下方依据区跳转原文段落。',
    keywords: ['审核后状态更新', '待确认更新', '更新依据', '重复按钮', '原文依据', '测试页'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'setting-editor-content-top-gap-after-mode-tabs-001',
    title: '设定编辑内容应与切换设定标签保持更大顶部间距',
    area: '作品工作台 / 设定页面 / 正式设定与人物设定编辑区',
    symptom: '设定页面顶部“切换设定 / 更新状态”标签行下方，设定名输入框贴得过近，整个编辑区显得压在顶部。',
    cause: '正式设定编辑器外层使用 pt-8，人物设定编辑器使用 py-3；顶部间距不足，但字段卡片之间的 gap 已经合适，不应通过改字段间距解决。',
    solution: '只增加编辑内容外层顶部 padding：作品设定结构化编辑区从 pt-8 调整为 pt-12，人物设定编辑区从 py-3 拆为 pb-3 pt-8，让整组内容整体下移，内部框间距保持不变。',
    prevention: '正式迁移测试锁定 workbenchSettingEditor 的 pt-12 和 workbenchRoleEditor 的 pt-8，避免后续优化字段间距时又把顶部距离压回去。',
    keywords: ['设定页面', '切换设定', '设定名', '顶部间距', '人物设定', 'pt-12', 'pt-8'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'male-protagonist-badge-color-conflict-001',
    title: '人物设定男主标签不应与选中底色同系',
    area: '作品工作台 / 左侧人物设定树 / 男主标签',
    symptom: '人物导航里的“男主”标签使用浅青底色，和当前选中态的浅蓝底太接近，选中后层次不明显。',
    cause: '男主标签沿用了与选中卡片相同的青蓝系背景和蓝绿色文字，缺少独立身份色。',
    solution: '将男主标签改为琥珀浅底配深琥珀字，并加细边框，让它在选中浅蓝底上也能清楚分开。',
    prevention: '导航树测试锁定男主标签使用暖色背景和深色文字，避免以后再回到浅青撞色方案。',
    keywords: ['男主', '标签颜色', '选中态', '浅青', '琥珀', '导航树'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'brainstorm-create-prompt-modal-position-drag-cursor-001',
    title: '创建提示词弹窗打开时应居中且标题栏应显示拖拽光标',
    area: '作品工作台 / 脑洞 / 提示词管理 / 创建提示词弹窗',
    symptom: '创建提示词弹窗打开后位置偏高，用户可以左右拖动但向下移动受限；鼠标按住标题栏时也没有明显的拖拽光标反馈。',
    cause: '创建提示词弹窗沿用旧的拖拽位置 storageId，本地保存过的上方位置和尺寸会继续覆盖新版默认居中；共享 AppModalShell 只有标题文字小块带 cursor-move，整条标题栏没有统一的拖拽光标。',
    solution: '将创建/编辑提示词弹窗切到新的 brainstorm_prompt_editor_centered_v3 位置记忆 key，并显式提供 x/y 为 0 的居中默认几何；AppModalShell 标题栏整行增加 cursor-move 和按下时的 active:cursor-grabbing。',
    prevention: '以后调整可拖拽弹窗的默认位置或尺寸时，若旧 localStorage 可能继续覆盖新版视觉，应同步更换稳定 storageId 或增加清理逻辑；共享标题栏拖拽区域必须覆盖用户可按住的整条标题栏。',
    keywords: ['创建提示词', '弹窗居中', '拖拽', '标题栏', 'cursor-move', 'storageId', 'AppModalShell'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'setting-editor-content-top-gap-second-pass-001',
    title: '设定编辑区与切换设定标签行的顶部间距应在所有设定类型中一致生效',
    area: '作品工作台 / 设定页面 / 正式设定与人物设定编辑区',
    symptom: '上一次只调整部分编辑器顶部 padding 后，用户在正式页面仍看到“设定名/人物姓名”所在首行距离“切换设定/更新状态”标签行过近，视觉上没有明显下移。',
    cause: '作品设定已选中和空态虽然改到 pt-12，但人物设定仍停留在 pt-8；同时 pt-12 在当前页面比例下变化不够明显，导致正式入口看起来仍像没有修复。',
    solution: '将作品设定空态、作品设定已选中态和人物设定编辑态的 xy-setting-name-editor 外层顶部 padding 统一提高到 pt-16，只移动整组内容，不改变字段框之间的 gap 和卡片内部间距。',
    prevention: '正式迁移测试统一锁定 workbenchSettingEditor 与 workbenchRoleEditor 的 xy-setting-name-editor 使用 pt-16，避免只改其中一个设定页面或回退到旧的 pt-12/pt-8。',
    keywords: ['设定页面', '切换设定', '设定名', '人物姓名', '顶部间距', 'pt-16', '同步移动'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'setting-editor-scrollbar-gutter-stable-001',
    title: '设定编辑区滚动条出现或消失时不应导致字段框横向跳动',
    area: '作品工作台 / 设定页面 / 作品设定与人物设定编辑区',
    symptom: '当人物设定字段内容增多或设定编辑区高度超过容器时，竖向滚动条出现会占用横向空间，导致字段框位置或宽度看起来发生轻微偏移。',
    cause: '作品设定和人物设定的页面级滚动容器、字段 textarea 没有统一预留 scrollbar gutter；滚动条只在内容溢出时占宽，非溢出状态和溢出状态的布局宽度不同。',
    solution: '给作品设定已选中态滚动容器、作品设定空态/普通字段 textarea、结构化字段 textarea、人物设定滚动容器、人物字段 textarea 和更新状态面板滚动容器增加 [scrollbar-gutter:stable]，让滚动条出现前后都按同一宽度计算。',
    prevention: '正式迁移测试锁定设定编辑区、人物设定编辑区和更新状态面板的 [scrollbar-gutter:stable]，以后新增同类设定滚动容器或自动增高 textarea 时也要预留稳定 gutter。',
    keywords: ['设定页面', '滚动条', 'scrollbar-gutter', '字段框', '人物设定', '作品设定', '横向偏移'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'shared-modal-centered-drag-two-axis-001',
    title: '居中弹窗首次拖动时应能同时上下左右移动',
    area: '共享弹窗 / 作品工作台 / 创建提示词',
    symptom: '创建提示词弹窗按住标题栏后可以明显左右移动，但上下拖动几乎没有反应。',
    cause: '弹窗首次拖动仍使用“父容器居中 + transform 偏移”坐标，纵向偏移上限又按弹窗高度压缩，高弹窗的纵向可移动范围过小。',
    solution: '按下共享弹窗标题栏时，先根据弹窗当前屏幕矩形转换成固定 left/top/width/height 几何，再以真实固定坐标计算水平和纵向位移。',
    prevention: '共享拖拽 Hook 的交互测试同时改变 clientX 和 clientY，并断言弹窗转为 fixed 后 left 与 top 都按差值更新。',
    keywords: ['创建提示词', '弹窗拖动', '上下移动', 'left', 'top', 'fixed', 'useDraggableModal'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'setting-editor-top-offset-missing-generated-utility-001',
    title: '设定页整组内容应真正与切换标签拉开距离',
    area: '作品工作台 / 设定 / 作品设定与人物设定编辑区',
    symptom: '源码已多次把编辑容器改为 pt-16，但运行软件中设定名或人物姓名首行仍紧贴“切换设定 / 更新状态”标签行，视觉上没有下移。',
    cause: '当前构建产物没有生成 .pt-16 工具类，元素上虽然写了类名，浏览器却没有任何可应用的 padding-top 规则。',
    solution: '新增项目共享类 xy-setting-editor-content-offset，显式设置 1.5rem 顶部留白；作品设定空态、作品设定已选中态和人物设定统一复用，整组内容下移且内部间距不变。',
    prevention: '对关键布局间距不只断言 JSX 中存在工具类；同时锁定实际 CSS 规则和所有兄弟编辑器入口的共享类使用次数。',
    keywords: ['设定页', '整体下移', '切换设定', 'padding-top', 'pt-16', 'CSS构建', '人物设定'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'setting-editor-top-offset-root-font-scale-001',
    title: 'Setting editor offset must override the legacy forced spacing',
    area: 'Workbench / Settings / work and role editors',
    symptom: 'The first setting field still appeared too close to the mode tabs after the shared offset class was added.',
    cause: 'A legacy .xy-setting-name-editor rule forced padding-top to 12px with !important, overriding the newer shared offset even though the 36px rule existed in the production CSS.',
    solution: 'Remove the legacy forced padding and make the combined editor offset selector the single 36px source for all work and role setting states.',
    prevention: 'For visible spacing changes, inspect computedStyle, matching rule priority, and element bounds in the built Electron renderer instead of checking only whether the new rule exists.',
    keywords: ['setting editor', 'top offset', 'important override', 'computedStyle', 'Electron validation'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'ai-output-title-and-config-border-consistency-001',
    title: 'AI output titles and model prompt frames must share formal typography and borders',
    area: 'Workbench / shared AI output and model prompt controls',
    symptom: 'The embedded AI output title was smaller and lighter than the setting name title, while model and prompt frames rendered with a pale cyan outline in every AI panel.',
    cause: 'AI output titles inherited the generic 1rem 500 20px floating-label style, and the writer theme remapped the CombinedAiConfigSelect border utility to the pale accent-border token.',
    solution: 'Apply the setting-name 1rem 900 24px typography to shared AI output titles and give every CombinedAiConfigSelect frame a dedicated #08AACE border rule that wins over theme remapping.',
    prevention: 'Keep output title typography and model prompt frame color behind shared semantic selectors, with source-contract tests covering all consumers instead of local page overrides.',
    keywords: ['AI output', 'setting name typography', 'model prompt frame', 'CombinedAiConfigSelect', '#08AACE'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'shared-modal-portal-scale-drag-regression-002',
    title: '创建提示词弹窗在软件缩放下必须能够上下拖动',
    area: '共享弹窗 / 作品工作台 / 脑洞 / 创建提示词',
    symptom: '上一次改为固定 left/top 坐标后，创建提示词弹窗仍然只能明显左右移动，上下拖动几乎没有效果。',
    cause: '弹窗通过 Portal 渲染在未缩放的 body 中，但拖拽 Hook 仍无条件使用 AppFrame 的全局缩放值计算鼠标位移和视口边界，导致高弹窗的纵向可移动范围被再次压缩。',
    solution: '让拖拽位移、尺寸边界和坐标归一化统一读取弹窗实际所在容器的缩放上下文；body Portal 弹窗按 1 倍计算，位于缩放根节点内的弹窗才使用应用缩放值。',
    prevention: '共享拖拽回归测试必须覆盖全局缩放不为 1、弹窗位于 body Portal、clientX/clientY 同时变化的组合，并断言 left 和 top 都按原始指针差值更新。',
    keywords: ['创建提示词', '上下拖动', 'Portal', '软件缩放', 'useDraggableModal', 'left', 'top'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'brainstorm-question-and-title-typography-consistency-001',
    title: '脑洞题材字段和脑洞名称应与人物姓名保持统一字样',
    area: '作品工作台 / 脑洞页面 / 题材字段与脑洞名称',
    symptom: '设定和人物页面已经统一到人物姓名的字体基准，但脑洞页的题材、故事主题等字段仍偏小偏粗，脑洞名称也依赖局部旧样式，切换页面时观感不一致。',
    cause: '脑洞问题字段继续复用紧凑文本框的 14px 样式，字段输入保留 font-bold；脑洞名称和 AI 输出名称只通过父级继承字号，未显式锁定共享字体规格。',
    solution: '新增脑洞问题字段语义类，统一输入内容为 1rem、500 字重，并将字段标题与脑洞名称、AI 输出名称统一到人物姓名标题的 1rem、900 字重；模型/提示词组合框继续由共享规则固定使用 #08AACE 边框。',
    prevention: '以后统一嵌入边框文字时，必须同时检查正式设定、人物、脑洞的字段输入、标题输入和共享模型提示词框，并通过页面级源码测试锁定语义类和共享边框规则。',
    keywords: ['脑洞页面', '题材', '故事主题', '脑洞名称', '人物姓名', '字体统一', '#08AACE'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'prompt-editor-centered-name-description-fields-001',
    title: '创建提示词弹窗应居中并统一名称说明字段样式',
    area: '提示词管理 / 创建与编辑提示词弹窗 / 名称和说明字段',
    symptom: '创建提示词弹窗会读取旧的拖拽位置而偏离屏幕中心；提示词名称和提示词说明仍使用细灰边框和较弱标签，与设定名的黑色嵌入标题框不一致。',
    cause: '通用提示词弹窗沿用 prompt_editor 的持久化几何，打开时优先恢复旧坐标；名称和说明继续复用 compact 浮动字段，没有使用人物姓名/设定名的标题、字号和粗边框基准。',
    solution: '共享弹窗增加 centerOnOpen 能力，通用与审核提示词弹窗每次打开重置为屏幕中心；名称和说明统一使用 2px 黑色边框、12px 圆角、透明嵌入标题、16px 标题和16px输入文字，说明保留多行编辑。',
    prevention: '新增可拖拽业务弹窗时明确区分“记忆位置”和“每次居中”；提示词元信息字段统一复用 xy-prompt-meta-field，不再单独拼接紧凑灰框。',
    keywords: ['创建提示词', '弹窗居中', '提示词名称', '提示词说明', 'WorkbenchNameField', 'centerOnOpen'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'setting-editor-top-label-offset-35px-001',
    title: '设定编辑区首行标题与上方横线间距统一为 35px',
    area: '作品工作台 / 设定 / 作品设定与人物设定编辑区',
    symptom: '设定名或人物姓名标题上沿到上方横线的距离需要精确统一为 35px，原共享间距多出 1px。',
    cause: '作品设定空态、作品设定已选中态和人物设定虽然已经复用共享偏移类，但共享值仍为 36px。',
    solution: '将 xy-setting-editor-content-offset 的唯一 padding-top 从 36px 调整为 35px，三个正式编辑状态同步生效。',
    prevention: '继续由单一共享类控制三个正式状态，并用源码回归断言锁定共享类使用次数和 35px 精确值，禁止增加页面级覆盖。',
    keywords: ['设定页面', '设定名', '人物姓名', '顶部间距', '35px', '共享样式'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'retired-setting-role-css-cleanup-001',
    title: '清理设定与人物页面已经退役的旧样式',
    area: '共享样式 / 设定页面 / 人物页面',
    symptom: '新版设定名、人物字段和状态控件已经落地后，样式文件中仍保留旧版大圆角设定名、紧凑人物姓名、身份与生存控件、胶囊尺寸控件等规则。',
    cause: '页面迁移时只停止使用旧类名，没有同步删除基础样式、水墨主题覆盖和依赖旧选择器的测试断言。',
    solution: '删除正式页面零引用的旧选择器及其主题覆盖，保留当前仍在使用的共享设定框、脑洞文本框和输入框尺寸调节规则，并更新相关测试。',
    prevention: '增加旧选择器残留门禁；以后替换同类 UI 时同时检查正式引用、基础样式、主题覆盖和测试，确认零引用后一次清理。',
    keywords: ['旧样式', '设定页面', '人物页面', 'CSS清理', '零引用', '回归门禁'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'top-test-button-full-page-navigation-001',
    title: '右上角测试按钮应直接进入测试板块页面',
    area: '软件顶部栏 / 测试板块入口',
    symptom: '点击软件右上角测试按钮时会打开覆盖当前页面的大弹窗，而不是进入完整的测试板块页面。',
    cause: '顶部按钮维护了一套独立的弹窗开关，并在应用外框中重复懒加载测试集合页面。',
    solution: '顶部按钮改为直接跳转测试板块正式路由，同时删除旧测试弹窗、弹窗状态和重复页面加载；UI库弹窗保持原样。',
    prevention: '用源码回归测试锁定右上角按钮必须导航到测试板块，并禁止测试弹窗状态和弹窗存储标识重新出现。',
    keywords: ['测试按钮', '测试板块', '页面跳转', '弹窗删除', '顶部栏'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'prompt-editor-default-size-and-resize-jump-001',
    title: '创建提示词弹窗尺寸过大且首次缩放跳变',
    area: '提示词管理 / 创建与编辑提示词弹窗 / 共享弹窗缩放',
    symptom: '普通创建提示词弹窗再次接近铺满屏幕；从右下角轻微缩小时，弹窗会在第一次移动时突然缩小一大截。',
    cause: '普通提示词弹窗使用全高布局且没有明确默认宽高；共享缩放上限只有视口的 80%，首次缩放会先把超过上限的实际尺寸强制压缩，再计算鼠标位移。',
    solution: '普通创建与编辑提示词统一为 980×680 的居中响应式尺寸；共享弹窗可用缩放范围提高到视口的 96%，使首次缩放以当前实际尺寸连续变化。',
    prevention: '回归测试锁定普通提示词弹窗默认尺寸，并模拟右下角仅移动 10px，断言宽高也只变化 10px；共享弹窗 Hook 依赖保持完整。',
    keywords: ['创建提示词', '弹窗高度', '右下角缩放', '尺寸跳变', '居中弹窗'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'brainstorm-empty-placeholder-typography-mismatch-001',
    title: '脑洞字段空值状态没有使用统一字体',
    area: '作品工作台 / 脑洞 / 题材与构思字段',
    symptom: '脑洞名称和已填写内容已经统一，但题材、故事主题、主角金手指、你的构思和补充内容为空时，提示文字仍显示为灰色粗体，看起来像没有完成字体统一。',
    cause: '正式字段的空值状态继续继承全局可见占位文字规则，并且文本框局部还保留 font-bold；原测试只展示已填写值，没有覆盖空字段。',
    solution: '为脑洞问题字段单独统一空值提示文字和已填写内容：使用相同字体、16px、500 字重和深色文字，同时移除文本框局部粗体。',
    prevention: '字体统一回归测试必须同时覆盖有值和空值占位状态，并禁止脑洞问题文本框重新使用 font-bold。',
    keywords: ['脑洞页面', '占位文字', '题材', '故事主题', '字体统一', '空值状态'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'prompt-content-label-fixed-embedded-title-001',
    title: '提示词内容标题应固定在上边框',
    area: '提示词管理、脑洞提示词、审核提示词编辑弹窗',
    symptom: '提示词内容为空时，标题会落到输入框内部；填写或聚焦后才移动到上边框，并且字体与提示词名称不一致。',
    cause: '普通和脑洞提示词内容继续使用会根据空值变化位置的浮动标签，审核提示词虽然固定，但仍使用较小字号。',
    solution: '普通和脑洞提示词内容改为固定的透明嵌入标题，审核提示词标题同步为16px粗体；三处都与提示词名称保持同一标题基准。',
    prevention: '回归测试锁定提示词内容必须使用固定嵌入标题和可访问名称，并禁止重新出现会随空值移动的label结构。',
    keywords: ['提示词内容', '固定标题', '嵌入边框', '提示词名称', '字体统一'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'setting-editor-top-spacing-test-18-migration-30px-001',
    title: '18号测试按30px迁入正式设定页面',
    area: '作品工作台 / 作品设定与人物设定编辑区',
    symptom: '设定编辑区顶部留白仍停留在之前的35px正式值，18号测试方案尚未按最终选择迁入。',
    cause: '顶部留白对比只存在于测试板块，正式页面继续使用共享的35px偏移。',
    solution: '按用户最终选择将共享顶部偏移改为30px，作品设定空态、已选中态和人物设定同步生效，并删除18号临时测试。',
    prevention: '正式迁移测试锁定三个编辑状态继续共用同一偏移类和30px精确值，测试集合清理门禁禁止18号入口回流。',
    keywords: ['18号测试', '设定页面', '顶部留白', '30px', '正式迁移'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'role-tree-outline-selection-test-16-migration-001',
    title: '16号测试的人物导航蓝框选中态迁入正式页面',
    area: '作品工作台 / 人物设定 / 左侧人物导航',
    symptom: '人物条目选中后整块变成浅蓝色，男主标签和文字在选中底色上不够清楚。',
    cause: '首次迁移只修改了旧人物侧栏，但正式设定页已经改用WorkbenchSettingTreeSidebar统一树；现用树的人物条目仍复用普通设定的浅蓝填充选中态。',
    solution: '在正式统一设定树中区分人物和普通设定：人物条目选中后使用白底、2px的#078FAE外框和灰色文字，普通设定继续保留原浅蓝选中态。',
    prevention: '回归测试直接渲染正式统一设定树并点击人物条目，锁定蓝色外框、白底、灰色文字及男主标签，同时保留旧侧栏的兼容断言。',
    keywords: ['16号测试', '人物导航', '选中状态', '蓝色外框', '#078FAE'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'text-audit-paragraph-selection-bd-formal-migration-001',
    title: '剧情审核段落选中采用BD方案并清除框外蓝色',
    area: '剧情审核 / 正文预览 / 段落选中状态',
    symptom: '段落选中不够明显，BD测试方案的蓝色阴影和外扩描边还会越过卡片底边，在蓝框外留下蓝色。',
    cause: '首次迁移把BD卡片样式接到了右侧审核标注列表，中间真正可点击的原文段落仍沿用只有蓝点的旧样式，因此用户实际操作路径没有变化。',
    solution: '把BD方案接到中间原文段落：选中段落显示蓝框、框内浅蓝底、蓝点和段落编号，不再显示右上角“当前选中”；未选中段落弱化为浅灰，并继续禁止外扩ring和投影。',
    prevention: '回归测试直接渲染可点击的ChapterReviewOriginalBody并检查选中、未选中和点击切换，同时锁定不显示“当前选中”、不预留右侧空位且不得包含蓝色shadow或ring。',
    keywords: ['剧情审核', '段落选中', '方案BD', '蓝色框', '阴影清理'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'detail-outline-title-count-backplate-seam-001',
    title: '章纲标题与字数之间不应露出边框痕迹',
    area: '章纲 / 章纲卡片与状态变化卡片 / 边框嵌入标题',
    symptom: '状态变化和0字之间会露出一小段边框线，其他章纲标题与字数组合也存在相同风险。',
    cause: '标题外层是普通行内文字，字数使用2ch左外边距；外边距不属于标题的背景绘制区域，因此底层边框始终可能从两者之间露出。',
    solution: '把章纲标题、状态变化和字数组合改成同一个inline-flex整体，使用内部2ch gap而不是字数外边距，让整组透明背板连续覆盖标题、间隔和字数。',
    prevention: '边框内同一行的标题与附加信息必须放在同一个布局盒内，间距使用内部gap，禁止用子元素margin制造背板无法覆盖的透明空隙。',
    keywords: ['章纲', '状态变化', '0字', '边框痕迹', '透明背板'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'vite-hmr-stale-renderer-recovery-001',
    title: '开发版热更新失效后不应继续显示旧界面',
    area: '桌面开发运行环境 / Vite热更新 / Electron渲染窗口',
    symptom: '多个已经写入正式源码并通过测试的界面改动，在当前打开的软件中同时没有效果。',
    cause: '开发服务长期运行期间删除测试页、调整大型组件后出现模块刷新失败和React Hook顺序错误，Electron窗口继续保留了部分旧模块状态。',
    solution: '确认当前窗口加载开发服务后执行一次后台整页重载；开发版新增热更新恢复机制，遇到模块失效或模块移除时自动完整重载当前页面，不关闭或新开软件窗口。',
    prevention: '以后正式迁移并删除测试模块时，自动化之外还要检查Vite失效事件；开发窗口收到invalidate或beforePrune后必须完整重载，禁止继续使用混合的新旧模块状态。',
    keywords: ['Vite', '热更新', 'Electron', '旧界面', '完整重载'],
    updatedAt: '2026-07-23',
  },
  {
    id: 'text-audit-apply-return-initial-view-001',
    title: '应用已接受修改后应回到剧情审核初始三栏',
    area: '剧情审核 / 文本审核逐段确认 / 应用已接受修改',
    symptom: '应用已接受修改后，原文与审核后草稿变成同一份内容，页面停留在逐段对比模式并显示无修改空白页，原文区域也随之消失。',
    cause: '保存正文后又把审核后草稿设置为同一份正文，但没有结束本轮审核状态；逐段对比发现零处差异后只能渲染空状态。',
    solution: '先把确认内容写回正文，再清除本轮审核输出、草稿、日志和后台任务状态，使页面退出逐段对比并回到章纲、原文、剧情审核初始三栏；正文继续显示应用后的内容。',
    prevention: 'Hook回归测试锁定处理顺序必须是写回正文、清理审核状态、显示成功提示，并禁止再次把应用后的正文写入审核后草稿。',
    keywords: ['剧情审核', '接受修改', '原文消失', '初始页面', '逐段对比'],
    updatedAt: '2026-07-23',
  },
];
